### DISCUSSION TITLE
I'm begging can someone help..? ;) Again dreeambooth doesn't work and crashes after 4% of training.. RTX 3060 12GB VRAM

### DISCUSSION THREAD

**Discussion by pablomx11** [d8ahazard/sd_dreambooth_extension#761] [Q&A]
Already up to date.
venv "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 590ff5ce5b2e4474f998421c8de99baf74c45b5b
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 55880895d6bdf3596db815cb62e22969e9910b7b
SD-WebUI revision: 590ff5ce5b2e4474f998421c8de99baf74c45b5b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.

#######################################################################################################

Launching Web UI with arguments: --xformers
SD-Webui API layer loaded
Loading config from: C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\models\Stable-diffusion\v2-1_768-nonema-pruned.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Loading weights [e1542d5a] from C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\models\Stable-diffusion\v2-1_768-nonema-pruned.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 4.5s (0.1s create model, 3.0s load weights).
Warning: Bad ui setting value: img2img/Mask mode/value: Draw mask; Default value "Inpaint masked" will be used instead.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Invalid model name.
Loading model from checkpoint.
Loading checkpoint...
v2 model loaded.
Converting unet...
Converting vae...
Converting text encoder...
Saving diffusion model...
Restored system models.
Checkpoint successfully extracted to C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\models\dreambooth\j1o2l3a768\working
Total images: 0
Total VRAM: 12
Wizard results:<br>Num Epochs: 150<br>Max Steps: 0
Saved settings.
Saved settings.
Custom model name is
Starting Dreambooth training...
Initializing dreambooth training...
Replace CrossAttention.forward to use xformers
Instance Bucket 0: Resolution (768, 768), Count: 15
Target Bucket 0: Resolution (768, 768), Count: 0
We need a total of 0 images.
Nothing to generate.
Injecting trainable lora...
CUDA SETUP: Loading binary C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Preparing dataset
Preparing dataset
Preparing Dataset (With Caching)
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.82it/s]
Train Bucket 1: Resolution (768, 768), Count: 15
Total images: 15
Total dataset length (steps): 15
Sched breakpoint is 1125
  ***** Running training *****
  Instance Images: 15
  Class Images: 0
  Total Examples: 15
  Num batches each epoch = 15
  Num Epochs = 150
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 0
  Total optimization steps = 2250
  Total training steps = 2250
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: True, Adam: True, Prec: bf16
  Gradient Checkpointing: True
  EMA: False
  LR: 2e-06)
Generating Samples:   0%|                 | 0/3 [00:00<?, ?it/s, loss=0.408, loss_avg=0.426, lr=0.0002, vram_usage=9.9]Exception saving sample: CUDA out of memory. Tried to allocate 1.27 GiB (GPU 0; 12.00 GiB total capacity; 9.91 GiB already allocated; 65.11 MiB free; 10.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 711, in save_weights
    s_image = s_pipeline(c.prompt, num_inference_steps=c.steps,
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 534, in __call__
    image = self.decode_latents(latents)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 341, in decode_latents
    image = self.vae.decode(latents).sample
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\vae.py", line 605, in decode
    decoded = self._decode(z).sample
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\vae.py", line 577, in _decode
    dec = self.decoder(z)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\vae.py", line 217, in forward
    sample = up_block(sample)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1335, in forward
    hidden_states = upsampler(hidden_states)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\resnet.py", line 139, in forward
    hidden_states = self.conv(hidden_states)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 1.27 GiB (GPU 0; 12.00 GiB total capacity; 9.91 GiB already allocated; 65.11 MiB free; 10.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py:415: FutureWarning: Dropping of nuisance columns in rolling operations is deprecated; in a future version this will raise TypeError. Select only valid columns before calling the operation. Dropped columns were Index(['Name'], dtype='object')
  all_df_loss = all_df_loss.rolling(smoothing_window).mean()
Steps:   0%|                           | 0/2250 [00:00<?, ?it/s, loss=0.408, loss_avg=0.426, lr=0.0002, vram_usage=9.9]Traceback (most recent call last):
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 561, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 973, in main
    return inner_loop()
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 116, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 829, in inner_loop
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 490, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\torch\amp\autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 392, in forward
    sample = self.mid_block(sample, emb, encoder_hidden_states=encoder_hidden_states)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 412, in forward
    hidden_states = self.resnets[0](hidden_states, temb)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\resnet.py", line 464, in forward
    hidden_states = self.conv1(hidden_states)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\pablo\OneDrive\Desktop\Si\2023\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
Steps:   3%|▌               | 75/2250 [00:00<00:02, 1023.07it/s, loss=0.408, loss_avg=0.426, lr=0.0002, vram_usage=9.9]
Training completed, reloading SD Model.
Restored system models.
Returning result: Exception training model: 'Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.'.

**Comment by pablomx11** [comment]
OK, I solved the problem.. myself.. ;) I trusted the settings (Performance Wizard WIP) but it should be changed to zero there in the settings.. ;) So maybe it's worth setting it to zero by default in these settings..? ;) Save Model Frequency (Epochs) 0 / Save Preview(s) Frequency (Epochs) 0

**Reply by rpgsolomaker** [reply]
> OK, I solved the problem.. myself.. ;) I trusted the settings (Performance Wizard WIP) but it should be changed to zero there in the settings.. ;) So maybe it's worth setting it to zero by default in these settings..? ;) Save Model Frequency (Epochs) 0 / Save Preview(s) Frequency (Epochs) 0

Would you mind sharing all the settings that you used? i'm having trouble training a model and i have a similar gpu. Thank you.

**Reply by pablomx11** [reply]
Save Model Frequency (Epochs) must be 0 and Save Preview(s) Frequency (Epochs) must be 0
