### ISSUE TITLE
Bug when starting training for the first time (Exception while training: CUDA error: invalid argument)

### ISSUE THREAD

**Issue by mikebind** [d8ahazard/sd_dreambooth_extension#115]
**Have you read the Readme?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is 3b3a8002da3a780c276934e8bcf308aa822f1e22
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

What I have is: 
`Dreambooth revision is 4684f0faea19c243216eac2278a42fcfcbbd756b
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

I installed Dreambooth extension today just before running, so it should be up to date.

**Describe the bug**

I created a new model, set the settings in the Train Model tab.  I accidentally clicked the Generate Ckpt button instead of the "Train" button (just mentioning in case this somehow lead to the issue).  Then clicked the "Train" button.  Class images were generated fine, but errors were thrown after caching latents but before training actually started (errors pasted below).

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Caching latents: 100%|███████████████████████████████████████████████████████████████| 130/130 [00:12<00:00, 10.41it/s]
 Scheduler Loaded
 Allocated: 0.1GB
 Reserved: 0.1GB

Steps:   0%|                                                                                  | 0/1300 [00:00<?, ?it/s] Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 6.3GB
 Reserved: 8.2GB

Traceback (most recent call last):
  File "D:\StableDiffusion\auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 923, in main
    accelerator.backward(loss)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 884, in backward
    loss.backward(**kwargs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 6.3GB
 Reserved: 10.4GB

Traceback (most recent call last):
  File "D:\StableDiffusion\auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 923, in main
    accelerator.backward(loss)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 884, in backward
    loss.backward(**kwargs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 6.3GB
 Reserved: 10.6GB

Traceback (most recent call last):
  File "D:\StableDiffusion\auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 923, in main
    accelerator.backward(loss)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 884, in backward
    loss.backward(**kwargs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 6.3GB
 Reserved: 10.6GB

Traceback (most recent call last):
  File "D:\StableDiffusion\auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 923, in main
    accelerator.backward(loss)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 884, in backward
    loss.backward(**kwargs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 6.3GB
 Reserved: 10.6GB

Traceback (most recent call last):
  File "D:\StableDiffusion\auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 923, in main
    accelerator.backward(loss)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 884, in backward
    loss.backward(**kwargs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 6.3GB
 Reserved: 10.6GB

Traceback (most recent call last):
  File "D:\StableDiffusion\auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 923, in main
    accelerator.backward(loss)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 884, in backward
    loss.backward(**kwargs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 6.3GB
 Reserved: 10.6GB

Traceback (most recent call last):
  File "D:\StableDiffusion\auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 923, in main
    accelerator.backward(loss)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 884, in backward
    loss.backward(**kwargs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 6.3GB
 Reserved: 10.6GB

Traceback (most recent call last):
  File "D:\StableDiffusion\auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 923, in main
    accelerator.backward(loss)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 884, in backward
    loss.backward(**kwargs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 6.3GB
 Reserved: 10.6GB

Traceback (most recent call last):
  File "D:\StableDiffusion\auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 923, in main
    accelerator.backward(loss)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 884, in backward
    loss.backward(**kwargs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 6.3GB
 Reserved: 10.6GB

Traceback (most recent call last):
  File "D:\StableDiffusion\auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 923, in main
    accelerator.backward(loss)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 884, in backward
    loss.backward(**kwargs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "D:\StableDiffusion\auto\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 CLEANUP:
 Allocated: 6.3GB
 Reserved: 10.6GB

 Cleanup Complete.
 Allocated: 6.3GB
 Reserved: 7.4GB

Steps:   0%|                                                                                  | 0/1300 [00:04<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 0.0GB

**Environment**
What OS? 
Windows 11
If Windows - WSL or native?
native
What GPU are you using?
NVIDIA RTX 3090

**Comment by stysmmaker** [comment]
Related to #48 (shouldn't be closed, see my comments)

**Comment by dx777** [comment]
Please fix it, it was working fine before, but now I have to put fp16, in order for it to work. And I'm using RTX 3090 24GB VRAM on Runpod.

**Comment by Lukium** [comment]
I've been troubleshooting this for the past few hours as I get the same errors. After doing several clean installs, it seems to be the case that as long as I **NEVER** use --xformers, that everything works fine. The moment I add --xformers to commandline_args, it breaks Dreambooth beyond repair (removing --xformers does not resolve the issue).

**Comment by d8ahazard** [comment]
So, I think I've come up with a version of the webui-user script that should properly install all the requirements and not throw any issues.

https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/webui-user-dreambooth.bat

**Comment by stysmmaker** [comment]
That should properly install them as you mention, but it won't resolve this issue. It's related to using the ShivamShrirao repo for diffusers, which is what `requirements.txt` will end up installing.

**Comment by Jonseed** [comment]
@stysmmaker was the ShivamShrirao diffusers version 0.7.2 or 0.8.0.dev0? I can no longer train today, and that could be the issue. I get CUDA OOM every time.

**Comment by stysmmaker** [comment]
ShivamShrirao was 0.8.0.dev0. This extension was recently updated to use the normal huggingface 0.7.2 version.

**Comment by Jonseed** [comment]
@stysmmaker how do we manually go back to ShivamShrirao's 0.8.0.dev0?

**Comment by stysmmaker** [comment]
It's going to prevent doing a `git pull` to update the extension (I'm not sure if the webui extension update feature cares about conflicts or not), but as a temporary fix, you can modify the `requirements.txt` in this repo and replace `diffusers==0.7.2` with `git+https://github.com/ShivamShrirao/diffusers.git#egg=diffusers`. Re-launching the webui entirely should then install it.
There's several other ways to do this but that's probably the fastest.

**Comment by Jonseed** [comment]
Hmm, I think I tried that, and it threw a bunch of errors. I'll try again.

**Comment by Jonseed** [comment]
Actually it worked this time... now running 0.8.0.dev0 diffusers... we'll see if this throws a CUDA OOM.

**Comment by Jonseed** [comment]
I can confirm that training works for me on 0.8.0.dev0, but **_NOT_** on 0.7.2 diffusers. On 0.7.2 I get OOM every time, no matter the settings.

**Comment by Lukium** [comment]
> So, I think I've come up with a version of the webui-user script that should properly install all the requirements and not throw any issues.
> 
> https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/webui-user-dreambooth.bat

I tried using the bat file, still get the same issue as soon as --xformers is enabled.

**Comment by d8ahazard** [comment]
It should be respecting the --xformers flag.

**Comment by d8ahazard** [comment]
So, I see the op @mikebind hasn't commented since this was open.

Are you still experiencing this issue? I've updated the diffusers version and added workarounds for the various issues fixed by the 0.8.0dev0 version, so we should be good in anything discussed. 

As such, I'd like to close this, and invite anybody having related issues to open a separate issue to keep the discussions concise.

**Comment by d8ahazard** [comment]
> I just updated everything (including this extension), dropped --xformers from my webui-user.bat command line arguments, and successfully started training. It's about 12% done now, so made it well past the first step where it was crashing before with the CUDA invalid argument error.

I'm gonna call that a success then. Feel free to re-open if something breaks.

**Comment by mikebind** [comment]
Just following up, training completed successfully and generated a usable model!  Thanks to everyone who contributed!

**Comment by Baquara** [comment]
Hello,

I am having the same problem as the (closed) issue #115 .
I tried the solutions from that thread, used the .sh file, removed --xformers etc but it is still not working.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.15.dev0+4c06c79.d20221201 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes.
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes.
**Have you updated Dreambooth to the latest revision?**
Yes.
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes.
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK.
**Describe the bug**

I am trying to train using the default settings from the Performance Wizard, but I am getting this:
```

Initializing dreambooth training...
Patching transformers to fix kwargs errors.
/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/generation_utils.py:24: FutureWarning: Importing `GenerationMixin` from `src/transformers/generation_utils.py` is deprecated and will be removed in Transformers v5. Import as `from transformers import GenerationMixin` instead.
  warnings.warn(
Replace CrossAttention.forward to use xformers
Checking concept: {'max_steps': -1, 'instance_data_dir': '/home/privateserver/Coding/sd/dataset/out/', 'class_data_dir': '', 'instance_prompt': '', 'class_prompt': '', 'save_sample_prompt': '', 'save_sample_template': '', 'instance_token': 'sks', 'class_token': 'person', 'num_class_images': 0, 'class_negative_prompt': '', 'class_guidance_scale': 7.5, 'class_infer_steps': 40, 'save_sample_negative_prompt': '', 'n_save_sample': 1, 'sample_seed': -1, 'save_guidance_scale': 7.5, 'save_infer_steps': 40}
Concept requires 0 images.
 Loaded model. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary /home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
 Scheduler, EMA Loaded. 
 Allocated: 3.6GB 
 Reserved: 3.7GB 

***** Running training *****
  Num examples = 29
  Num batches each epoch = 29
  Num Epochs = 100
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 2900
  Actual steps: 2900
   Training settings: CPU: False Adam: True, Prec: bf16, Grad: True, TextTr: False EM: False, LR: 2e-06 LORA:False 
 Allocated: 3.6GB 
 Reserved: 3.7GB 

Steps:   0%|                                                                                                                                           | 0/2900 [00:00<?, ?it/s] Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1. 
 Allocated: 4.1GB 
 Reserved: 5.5GB 

Traceback (most recent call last):
  File "/home/privateserver/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1041, in main
    accelerator.backward(loss)
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1314, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 146, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/home/privateserver/xformers/xformers/ops/memory_efficient_attention.py", line 422, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |    4180 MB |    5505 MB |   20177 MB |   15997 MB |
|       from large pool |    4103 MB |    5387 MB |   19734 MB |   15630 MB |
|       from small pool |      77 MB |     119 MB |     443 MB |     366 MB |
|---------------------------------------------------------------------------|
| Active memory         |    4180 MB |    5505 MB |   20177 MB |   15997 MB |
|       from large pool |    4103 MB |    5387 MB |   19734 MB |   15630 MB |
|       from small pool |      77 MB |     119 MB |     443 MB |     366 MB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |    5586 MB |    5586 MB |    8368 MB |    2782 MB |
|       from large pool |    5460 MB |    5460 MB |    8162 MB |    2702 MB |
|       from small pool |     126 MB |     126 MB |     206 MB |      80 MB |
|---------------------------------------------------------------------------|
| Non-releasable memory |    1179 MB |    1260 MB |   18897 MB |   17718 MB |
|       from large pool |    1170 MB |    1239 MB |   18379 MB |   17208 MB |
|       from small pool |       8 MB |      37 MB |     518 MB |     509 MB |
|---------------------------------------------------------------------------|
| Allocations           |    1434    |    1723    |    6158    |    4724    |
|       from large pool |     422    |     542    |    2157    |    1735    |
|       from small pool |    1012    |    1184    |    4001    |    2989    |
|---------------------------------------------------------------------------|
| Active allocs         |    1434    |    1723    |    6158    |    4724    |
|       from large pool |     422    |     542    |    2157    |    1735    |
|       from small pool |    1012    |    1184    |    4001    |    2989    |
|---------------------------------------------------------------------------|
| GPU reserved segments |     191    |     191    |     342    |     151    |
|       from large pool |     128    |     128    |     239    |     111    |
|       from small pool |      63    |      63    |     103    |      40    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |      84    |     163    |    2097    |    2013    |
|       from large pool |      28    |      61    |    1163    |    1135    |
|       from small pool |      56    |     103    |     934    |     878    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|

 CLEANUP:  
 Allocated: 4.1GB 
 Reserved: 5.5GB 

 Cleanup completed. 
 Allocated: 4.1GB 
 Reserved: 5.2GB 

 Cleanup Complete. 
 Allocated: 4.1GB 
 Reserved: 5.2GB 

Steps:   0%|                                                                                                                                           | 0/2900 [00:01<?, ?it/s]
 Training completed, reloading SD Model. 
 Allocated: 0.0GB 
 Reserved: 4.1GB 

Memory output: {}
 Restored system models. 
 Allocated: 2.7GB 
 Reserved: 4.1GB 

Returning result: Training finished. Total lifetime steps: 0 



```



**Provide logs**

See above.

**Environment**

What OS?

Arch Linux, 6.0.11-arch1-1

If Windows - WSL or native?

Native Linux.

What GPU are you using?

RTX 3060 12GB

**Screenshots/Config**

![image](https://user-images.githubusercontent.com/9168959/207234430-dc5a604a-ee54-414a-8201-97fdb0937b0a.png)

**Comment by wildfield** [comment]
@Baquara I'm not sure if it's the same issue that I had, but I believe it's due to torch <-> CUDA version incompatibility

WebUI installs torch-1.12 which uses cuda-11.3. So either:
1. From webui venv uninstall torch and reinstall the latest one (https://pytorch.org/get-started/locally/)
Or: 2. Install 11.3 cuda

I found that option 1 is easier so that's what I did, but it may cause other issues

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
