### ISSUE TITLE
That One Issue Where We're Discussing Compiling Alternate Versions of 8Bit Adam DLLS

### ISSUE THREAD

**Issue by Vininski** [d8ahazard/sd_dreambooth_extension#117]
**Have you read the Readme?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes but the revision numbers do not match below. I've reinstalled the extension and restarted web ui multiple times now following the steps mentioned in multiple other issues.
**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

Dreambooth revision is 3b3a8002da3a780c276934e8bcf308aa822f1e22
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

**Describe the bug**
Training of a new dreambooth model fails at step 0.
**Provide logs**
```
`X:\stable-diffusion-webui>git pull
Already up to date.
venv "X:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: ac085628540d0ec6a988fad93f5b8f2154209571
Installing requirements for Web UI
loading Dreambooth reqs from X:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt
Checking Dreambooth requirements.
Checking torch and torchvision versions
Dreambooth revision is 4684f0faea19c243216eac2278a42fcfcbbd756b
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Copying 8Bit Adam files for Windows.

Launching Web UI with arguments: --opt-split-attention --listen --autolaunch --enable-insecure-extension-access
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [81761151] from X:\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.ckpt
Global Step: 840000
Applying cross attention optimization (Doggettx).
Model loaded.

Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary X:\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
Caching latents: 100%|███████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.01s/it]
 Scheduler Loaded
 Allocated: 0.0GB
 Reserved: 0.0GB

Steps:   0%|                                                                                  | 0/1000 [00:00<?, ?it/s]Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Press any key to continue . . .
```

**Environment**
What OS? Windows 10
If Windows - WSL or native? Native
What GPU are you using? 1080ti 11GB

**Comment by d8ahazard** [comment]
Hey there.

If you're still experiencing this issue, try installing the 116 CUDA toolkit from Nvida:

https://developer.nvidia.com/cuda-11-6-0-download-archive

**Comment by james-things** [comment]
> Hey there.
> 
> If you're still experiencing this issue, try installing the 116 CUDA toolkit from Nvida:
> 
> https://developer.nvidia.com/cuda-11-6-0-download-archive

Unfortunately the problem persists with pascal cards on 116 in Windows, which I think is everyone who is running into this issue. 

I have been digging in to this issue for a bit in my (limited) spare time; looking at the Makefile for bitsandbytes (attached below), it appears that a GPU architecture-specific CUDA kernel is compiled before the so/dll is created. I would venture to guess that this is the source of the error message that amounts to "no matching kernel found." The trouble for me is that I unfortunately I am not familiar with cpp and so I do not know how to compile this dll as of yet. I have had time to research the basics but there is still more work to go in figuring out what I would need to know.

If we could get someone more experienced to translate the bitsandbytes linux Makefile into a Windows build script using like Mingw to build, I think that would solve the problem. In the meantime, hopefully I can figure it out. The one guy who managed to do it and shared about it sounded like he struggled and didn't share his precise method.

**Comment by Vininski** [comment]
Finally got a chance to try this but unfortunately I get the same error. After reading the discussion here: https://github.com/d8ahazard/sd_dreambooth_extension/discussions/99 It seems I'll just have to try this in WSL until the Windows/1080ti/8bitadam issue is resolved.

**Comment by james-things** [comment]
> Finally got a chance to try this but unfortunately I get the same error. After reading the discussion here: https://github.com/d8ahazard/sd_dreambooth_extension/discussions/99 It seems I'll just have to try this in WSL until the Windows/1080ti/8bitadam issue is resolved.

Were you able to get it running under WSL? I ask because I have looked into this issue a ton and I think I understand what is going on.

When building the DLL the compute capabilities are specified; if you look at the makefile for bnb, it will suggest a default build command as something like:

make cuda11x CUDA_VERSION=116

However if you look at how the script flows, 116 will not include a Pascal compatible kernel. You instead can pass "all" to build for all CUDA versions.

I was able to compile a "cudaall" version of the linux so file in this way. If it isn't working on WSL let me know, because this should be the solution. I compiled it right before leaving for a trip, so I haven't been able to try running this ext under WSL yet.

At this point I am 99% sure that translating the execution of:

make cuda11x CUDA_VERSION=all

into a MSVC build command is the solution to get this running natively in Windows. New territory for me but I will try when I get back from my trip. I uploaded the Linux compiled file to a repo so if anyone needs lmk and I will link. It may be the case that on WSL it just works without intervention anyhow.

**Comment by d8ahazard** [comment]
> > Finally got a chance to try this but unfortunately I get the same error. After reading the discussion here: #99 It seems I'll just have to try this in WSL until the Windows/1080ti/8bitadam issue is resolved.
> 
> Were you able to get it running under WSL? I ask because I have looked into this issue a ton and I think I understand what is going on.
> 
> When building the DLL the compute capabilities are specified; if you look at the makefile for bitsandbytes, it will suggest a default build command as something like:
> 
> make cuda11x CUDA_VERSION=116
> 
> However if you look at how the script flows, 116 will not include a Pascal compatible kernel. You instead can pass "all" to build for all CUDA versions.
> 
> I was able to compile a "cudaall" version of the linux so file in this way. If it isn't working on WSL let me know, because this should be the solution. I compiled it right before leaving for a trip, so I haven't been able to try running this ext under WSL yet.
> 
> At this point I am 99% sure that translating the execution of:
> 
> make cuda11x CUDA_VERSION=all
> 
> into a MSVC build command is the solution to get this running natively in Windows. New territory for me but I will try when I get back from my trip. I uploaded the Linux compiled file to a repo so if anyone needs lmk and I will link. It may be the case that on WSL it just works without intervention anyhow.

Any chance you could build a pascal/all kernel capable version of the DLLs for windows? I think that's one of the big issues people are running into - that the precompiled dlls I have dont' have the right instructions for their GPUs.

Haven't had a chance to sort out how to build them for windoze, but if you've got the env already set up, maybe you could hook us up?

**Comment by james-things** [comment]
> Any chance you could build a pascal/all kernel capable version of the DLLs for windows? I think that's one of the big issues people are running into - that the precompiled dlls I have dont' have the right instructions for their GPUs.
> 
> Haven't had a chance to sort out how to build them for windoze, but if you've got the env already set up, maybe you could hook us up?

That is 100% my plan. I unfortunately do not have the environment fully set up nor know exactly how to compile for cpp under Windows quite yet. I am a grad student (software) so my time is a bit limited right now, but figuring out how to make things work in miscellaneous languages and environments has been my life for the last couple years, so I am confident I can figure it out given enough time. I have nvcc working under Windows so I think I just need to bridge things to MSVC now. 

I'll be traveling today, I may have time to take a crack at it tonight, either way I'll for sure be working on it and as soon as I get it I will share here.

**Comment by sgsdxzy** [comment]
> > Any chance you could build a pascal/all kernel capable version of the DLLs for windows? I think that's one of the big issues people are running into - that the precompiled dlls I have dont' have the right instructions for their GPUs.
> > Haven't had a chance to sort out how to build them for windoze, but if you've got the env already set up, maybe you could hook us up?
> 
> That is 100% my plan. I unfortunately do not have the environment fully set up nor know exactly how to compile for cpp under Windows quite yet. I am a grad student (software) so my time is a bit limited right now, but figuring out how to make things work in miscellaneous languages and environments has been my life for the last couple years, so I am confident I can figure it out given enough time. I have nvcc working under Windows so I think I just need to bridge things to MSVC now.
> 
> I'll be traveling today, I may have time to take a crack at it tonight, either way I'll for sure be working on it and as soon as I get it I will share here.

Can I make a humble request that you also built for cu113 under Windows? Then we can avoid using a version different from base webui, and also enable the integration of ColossalAI, which I personally want to test because it offers to train under 8G, and 8G is a game changer.

**Comment by james-things** [comment]
@sgsdxzy there are definitely a ton of variables as to how and if it will work, but I will compile for as much as I can once I get it working, which leads me to-

Just an update, I've somewhat figured out compiling on windows - built kernels and ops objects but failing to link. I believe it is over dependencies, so I will try to debug it over the next day or two. A bit tired from traveling today so better to take another go at it sometime soon. I will keep you all posted, I know a lot of people would be very happy to have this working, myself included!

**Comment by d8ahazard** [comment]
> @sgsdxzy there are definitely a ton of variables as to how and if it will work, but I will compile for as much as I can once I get it working, which leads me to-
> 
> Just an update, I've somewhat figured out compiling on windows - built kernels and ops objects but failing to link. I believe it is over dependencies, so I will try to debug it over the next day or two. There were a few dependency steps in the (not at all so detailed) instructions I found on the bnb repo that I skipped, but I wanted to see how far I could get first.
> 
> I'm bit tired from traveling today so better to take another go at it sometime very soon. I will keep you all posted, I know a lot of people would be very happy to have this working, myself included!

Best of luck. I spent the past few hours trying to compile it, but keep getting various errors. Thought I was making headway, but I'm about to the point where I'm stumped.

**Comment by d8ahazard** [comment]
I suppose I could share what I came up with, although it's probably not nearly as far as you've gotten. But hey, everything helps, right?

```MKFILE_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
ROOT_DIR := $(patsubst %/,%,$(dir $(MKFILE_PATH)))

#Latest cygwin
GPP:= C:/cygwin64/bin/g++.exe
#Tried with v118, got worse issues. Might have to stick with 116?
CUDA_HOME:= C:/Progra~1/NVIDIA~2/CUDA/v11.8
CUDA_VERSION="118"
LIB := -L $(CUDA_HOME)/lib64 -lcudart -lcublas -lcublasLt -lcurand -lcusparse -L $(CONDA_PREFIX)/lib

# Building with 113 still fails, but works better than 118
#CUDA_HOME:= C:/Progra~1/NVIDIA~2/CUDA/v11.3
#CUDA_VERSION="113"
#LIB := -L $(CUDA_HOME)/lib/x64 -lcudart -lcublas -lcublasLt -lcurand -lcusparse -L $(CONDA_PREFIX)/lib

NVCC := $(CUDA_HOME)/bin/nvcc.exe

###########################################

CSRC := $(ROOT_DIR)/csrc
BUILD_DIR:= $(ROOT_DIR)/build

FILES_CUDA := $(CSRC)/ops.cu $(CSRC)/kernels.cu
FILES_CPP := $(CSRC)/common.cpp $(CSRC)/cpu_ops.cpp $(CSRC)/pythonInterface.cpp

INCLUDE :=  -I $(CUDA_HOME)/include -I $(ROOT_DIR)/csrc -I $(CONDA_PREFIX)/include -I $(ROOT_DIR)/dependencies/cub -I $(ROOT_DIR)/include

# NVIDIA NVCC compilation flags
COMPUTE_CAPABILITY := -gencode arch=compute_60,code=sm_60 # Pascal
COMPUTE_CAPABILITY += -gencode arch=compute_61,code=sm_61 # Pascal
COMPUTE_CAPABILITY += -gencode arch=compute_70,code=sm_70 # Volta
COMPUTE_CAPABILITY += -gencode arch=compute_72,code=sm_72 # Volta 

CC_CUDA11x := -gencode arch=compute_75,code=sm_75
CC_CUDA11x += -gencode arch=compute_80,code=sm_80
CC_CUDA11x += -gencode arch=compute_86,code=sm_86

CC_cublasLt110 := -gencode arch=compute_75,code=sm_75
CC_cublasLt110 += -gencode arch=compute_80,code=sm_80

CC_cublasLt111 := -gencode arch=compute_75,code=sm_75
CC_cublasLt111 += -gencode arch=compute_80,code=sm_80
CC_cublasLt111 += -gencode arch=compute_86,code=sm_86


all: $(ROOT_DIR)/dependencies/cub $(BUILD_DIR) env
	$(NVCC) $(COMPUTE_CAPABILITY) -Xcompiler '-fPIC' --use_fast_math -Xptxas=-v -dc $(FILES_CUDA) $(INCLUDE) $(LIB) --output-directory $(BUILD_DIR) 
	$(NVCC) $(COMPUTE_CAPABILITY) -Xcompiler '-fPIC' -dlink $(BUILD_DIR)/ops.obj $(BUILD_DIR)/kernels.obj -o $(BUILD_DIR)/link.o 
	$(GPP) -std=c++14 -DBUILD_CUDA -shared -fPIC $(INCLUDE) $(BUILD_DIR)/ops.obj $(BUILD_DIR)/kernels.obj $(BUILD_DIR)/link.o $(FILES_CPP) -o ./bitsandbytes/libbitsandbytes_cuda$(CUDA_VERSION).so $(LIB)

cuda11x: $(BUILD_DIR) env
	$(NVCC) $(CC_cublasLt111) -Xcompiler '-fPIC' --use_fast_math -Xptxas=-v -dc $(FILES_CUDA) $(INCLUDE) $(LIB) --output-directory $(BUILD_DIR)
	$(NVCC) $(CC_cublasLt111) -Xcompiler '-fPIC' -dlink $(BUILD_DIR)/ops.obj $(BUILD_DIR)/kernels.obj -o $(BUILD_DIR)/link.o 
	$(GPP) -std=c++14 -DBUILD_CUDA -shared -fPIC $(INCLUDE) $(BUILD_DIR)/ops.obj $(BUILD_DIR)/kernels.obj $(BUILD_DIR)/link.o $(FILES_CPP) -o ./bitsandbytes/libbitsandbytes_cuda$(CUDA_VERSION).dll $(LIB)

env:

$(BUILD_DIR):
	mkdir -p build
	mkdir -p dependencies

$(ROOT_DIR)/dependencies/cub:
	git clone https://github.com/NVlabs/cub $(ROOT_DIR)/dependencies/cub
	cd dependencies/cub; git checkout 1.11.0

clean:
	rm build/* 

cleaneggs:
	rm -rf *.egg*

cleanlibs:
	rm ./bitsandbytes/libbitsandbytes*.so
```

**Comment by d8ahazard** [comment]
> > Any chance you could build a pascal/all kernel capable version of the DLLs for windows? I think that's one of the big issues people are running into - that the precompiled dlls I have dont' have the right instructions for their GPUs.
> > Haven't had a chance to sort out how to build them for windoze, but if you've got the env already set up, maybe you could hook us up?
> 
> That is 100% my plan. I unfortunately do not have the environment fully set up nor know exactly how to compile for cpp under Windows quite yet. I am a grad student (software) so my time is a bit limited right now, but figuring out how to make things work in miscellaneous languages and environments has been my life for the last couple years, so I am confident I can figure it out given enough time. I have nvcc working under Windows so I think I just need to bridge things to MSVC now.
> 
> I'll be traveling today, I may have time to take a crack at it tonight, either way I'll for sure be working on it and as soon as I get it I will share here.

Any luck with this? :P

**Comment by james-things** [comment]
> Any luck with this? :P

Sorry for the delay in responding - unfortunately I spent much of the available time I had trying to get it to build with gcc within msys2, since that seemed like it might be closer to 1:1 translation of the makefile's procedure. Unfortunately I ended up in horrendous dependency hell, but I didn't delete what progress I made.

This lead me to think that building a project in MSVC is a better route, since that appears to be the only official CUDA integration in Windows, and I did read somewhere that it won't work unless done through this integration. I made up a basic project but ran out of free time ahead of the holiday. Unfortunately I have finals this week so I have put things on hold. but I will get back to it sometime next week when I have free time again. :)

**Comment by d8ahazard** [comment]
> > Any luck with this? :P
> 
> Sorry for the delay in responding - unfortunately I spent much of the available time I had trying to get it to build with gcc within msys2, since that seemed like it might be closer to 1:1 translation of the makefile's procedure. Unfortunately I ended up in horrendous dependency hell on the last step, but I didn't delete what progress I made.
> 
> This lead me to think that building a project in MSVC is a better route, since that appears to be the only official CUDA integration in Windows, and I did read somewhere that it won't work unless done through this integration. I made up a basic project but ran out of free time ahead of the holiday. Unfortunately I have finals this week so I have put things on hold, but I will get back to it sometime next week when I have free time again. :)

I have a sneaking suspicion that we can't compile it for < 116 version, but regardless, I had a helluva time even getting it to start failing in the later stages of compiling. Still, fingers crossed you can get it going.

**Comment by james-things** [comment]
> I have a sneaking suspicion that we can't compile it for < 116 version, but regardless, I had a helluva time even getting it to start failing in the later stages of compiling. Still, fingers crossed you can get it going.

I think I may have done it!!

(Thanks to this wonderful post: https://github.com/TimDettmers/bitsandbytes/issues/30#issuecomment-1330951753)

The instructions didn't work exactly as written but I just had to tinker with building pthread-win32 and got it working. There were a number of warnings though so no guarantees that it is without issues. I created a repo for the initial build, I am very tired so I will play with it more tomorrow but I am currently training at 1.2 it/s on my 1080Ti with a hard thermal cap of 68F, so it certainly seems to be working!

https://github.com/james-things/bitsandbytes-prebuilt-all_arch

You will have to point the extension to the new dll name or rename the dll to match the old one for now. I will tinker with it some more the next time I feel like procrastinating, haha.

**Comment by james-things** [comment]
I have trained a few trial models successfully on the 1080Ti using the dll I posted in the comment above now, so it seems to be what we needed for Pascal. 

To clarify what the difference with this dll is from the cuda116 one: it includes kernel support for "all" GPU architectures. It looks like this should be the last 4 generations. 

However, I am not sure if the fact that was compiled on my Pascal series GPU means that it will either not work or present reduced optimizations for those running >= 20 series. I would imagine this would be the case, because I got some weird warnings while compiling that seemed to suggest unsupported code.

I am not sure if the cuda version ran by the user matters a ton, if it is within the compatible range, or if this will only work on 11.6 because I compiled it on 11.6. I believe the former is the case, so hopefully this is a step towards resolving cu116 dependency.

Does anyone have cu113 installed (and ideally a pascal card) who could test it?

**Comment by d8ahazard** [comment]
> I have trained a few trial models successfully on the 1080Ti using the dll I posted in the comment above now, so it seems to be what we needed for Windows Dreambooth on Pascal!
> 
> To clarify what the difference with this dll is from the cuda116 one: it includes kernel support for "all" GPU architectures, rather than just for the newer cards. It looks like this should be the last 4 generations. You will notice a much larger file size; I presume this is the reason.
> 
> However, I am not sure if the fact that was compiled on my Pascal series GPU means that it will either not work or present reduced optimizations for those running >= 20 series. I would imagine this would be the case, because I got some weird warnings while compiling that seemed to suggest unsupported code.
> 
> I am not sure if the cuda version ran by the user matters a ton, if it is within the compatible range, or if this will only work on 11.6 because I compiled it on 11.6. I believe the former is the case, so hopefully this is a step towards resolving cu116 dependency.
> 
> Does anyone have cu113 installed (and ideally a pascal card) who could test it? It is such a bear to install cuda environments, lol.

Sounds promising!

A. Awesome work, and thank you.

B. I don't have a 1080 anywhere, but I can at least test with CU113 on my "other" GPU without affecting my development environment. I'll try to give it a go after I eat some dinner. I have a feeling it's not going to work, as I seem to recall getting a *lot* of errors when I tried compiling on CU113, to where I had to bump up to 116 to even get as far as I did in failing. 

C. Regardless, support for 116 for *all* reasonable architectures is better than none at all, so IMHO, you're a damned legend for doing this much work to make one DLL to add support for a small subset of people running a marginalized operating system. That's kind or a repeat of A, but it deserves it's own point anyway. ;)

**Comment by NagashSzarekh** [comment]
Just for additional confirmation I can confirm the new DLL is also working on my Titan Xp

**Comment by james-things** [comment]
> Just for additional confirmation I can confirm the new DLL is also working on my Titan Xp

Awesome, thank you for reporting back, I'm glad people other than myself can benefit from this! I have been having so much fun training models while studying for finals, haha.

**Comment by d8ahazard** [comment]
So, I suck, and haven't had a chance to try with CU113. Anybody else have a minute to test and verify so I can add this to main along with the V2 support? :P

**Comment by d8ahazard** [comment]
Can't say for *sure* that it'll train on CU113 as my other box only has 8GB or RAM, but I reverted to CU113 and started training, and it didn't puke up any specific BNB errors.

**Comment by james-things** [comment]
> So, I suck, and haven't had a chance to try with CU113. Anybody else have a minute to test and verify so I can add this to main along with the V2 support? :P

One consideration with regard to this -

While building the kernels.cu on my machine, the following warning is printed to the console repeatedly:

`CUDACOMPILE : ptxas warning : Value of threads per SM for entry _Z9kQuantizePfS_Phi is out of range. 
.minnctapersm will be ignored`

This doesn't break the build, and we can see that the dll does work, but it does make me worry that the dll could potentially in some way work less well for people who are using the originally provided one successfully. I haven't had enough time to research it properly, but it makes me wonder if say, I am compiling kernels for cards with newer architecture than my own, for example.  In this case, perhaps certain optimizations or features are being ignored. Whether or not this has any bearing on dreambooth's use of bitsandbytes, I don't really have any idea though, lol.

I guess my point is, it may be wise to incorporate is as an alternative option somehow, such that people can enable it if needed, either that or get some side by side testing on more modern hardware. In theory, loss of computational precision could lead to lower training quality, though I am a little to naive to what is going on under the hood here to know if that would apply. Just food for thought for now

**Comment by infacta-user** [comment]
I was also having this error, the new DLL worked for my tesla m40. Thanks!

**Comment by d8ahazard** [comment]
This has been implemented fully in the latest release.

**Comment by Vininski** [comment]
Legends! I can't wait to try this out.
