### ISSUE TITLE
LORA training: Sample Generation uses massive amounts of VRam

### ISSUE THREAD

**Issue by ElliottLester** [d8ahazard/sd_dreambooth_extension#1184]
Thanks for taking the time to look at this if I should post it somewhere else let me know.
I have been trying to get this working on and off for about 2 months it was working in February but I have been unable to get it working recently.
 
### 0. Initial troubleshooting
Full setup steps: (maybe I'm doing something silly)
```
cd ~
git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git
cd stable-diffusion-webui/extensions
git clone https://github.com/d8ahazard/sd_dreambooth_extension.git
cd ..
echo 'export COMMANDLINE_ARGS="--listen --enable-insecure-extension-access --no-half --xformers --api"' >> webui-user.sh
echo 'export REQS_FILE="./extensions/sd_dreambooth_extension/requirements.txt"' >> webui-user.sh
python3 -m venv venv && source venv/bin/activate
pip install xformers-0.0.18-cp310-cp310-manylinux2014_x86_64.whl
ln -s ~/stable-diffusion-webui.backup/PreProcess PreProcess # for dataset

./webui.sh
```
### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
[+] xformers version 0.0.18 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments: --listen --enable-insecure-extension-access --no-half --xformers --api
#######################################################################################################
```

### 2. Describe the bug

Generating samples during training seems to consume massive amounts of VRam.

Steps to reproduce:
create model 
click settings performance wizard
disable EMA (because this option become unavailable after enabling LORA but is still enabled in the config) 
enable LORA
click training wizard person
populate dataset etc...
click TRAIN

memory usage it reported by nvtop "launch.py" is the only command currently running
With EMA enabled
Base load on startup is 5.4G VRam
sample generation  around 9.2G VRAM
training steps is around 11.45G VRAM sustained
sample generation exceeds 23.68GB  VRAM
with EMA disabled 
training steps is around 8.84G VRAM sustained
sample generation exceeds 23.68GB  VRAM

The crash takes longer the higher the "Save Preview(s) Frequency (Epochs)" is set.

Expected behavior:
Sample generation should fit in VRam.

**Screenshots/Config**
```
{
    "adamw_weight_decay": 0.01,
    "adaptation_beta1": 0,
    "adaptation_beta2": 0,
    "adaptation_d0": 1e-08,
    "adaptation_eps": 1e-08,
    "attention": "xformers",
    "cache_latents": true,
    "clip_skip": 1,
    "concepts_list": [
        {
            "class_data_dir": "/home/user/stable-diffusion-webui/models/dreambooth/ClippyA/classifiers_0",
            "class_guidance_scale": 1,
            "class_infer_steps": 10,
            "class_negative_prompt": "",
            "class_prompt": "a picture of a cartoon paperclip with eyes",
            "class_token": "paperclip",
            "instance_data_dir": "PreProcess/clippy/",
            "instance_prompt": "clippy",
            "instance_token": "clippy",
            "is_valid": true,
            "n_save_sample": 0,
            "num_class_images_per": 5,
            "sample_seed": -1,
            "save_guidance_scale": 1,
            "save_infer_steps": 10,
            "save_sample_negative_prompt": "",
            "save_sample_prompt": "",
            "save_sample_template": ""
        }
    ],
    "concepts_path": "",
    "custom_model_name": "",
    "noise_scheduler": "DDPM",
    "deterministic": false,
    "ema_predict": false,
    "epoch": 25,
    "epoch_pause_frequency": 0,
    "epoch_pause_time": 0,
    "freeze_clip_normalization": false,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": false,
    "gradient_set_to_none": true,
    "graph_smoothing": 50,
    "half_model": false,
    "train_unfrozen": false,
    "has_ema": false,
    "hflip": false,
    "infer_ema": false,
    "initial_revision": 0,
    "learning_rate": 0.0001,
    "learning_rate_min": 1e-06,
    "lifetime_revision": 0,
    "lora_learning_rate": 0.0001,
    "lora_model_name": "",
    "lora_unet_rank": 4,
    "lora_txt_rank": 4,
    "lora_txt_learning_rate": 5e-05,
    "lora_txt_weight": 1,
    "lora_weight": 1,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "constant_with_warmup",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "mixed_precision": "bf16",
    "model_name": "CilppyB",
    "model_dir": "/home/user/stable-diffusion-webui/models/dreambooth/CilppyB",
    "model_path": "/home/user/stable-diffusion-webui/models/dreambooth/CilppyB",
    "num_train_epochs": 150,
    "offset_noise": 0,
    "optimizer": "8bit AdamW",
    "pad_tokens": true,
    "pretrained_model_name_or_path": "/home/user/stable-diffusion-webui/models/dreambooth/CilppyB/working",
    "pretrained_vae_name_or_path": null,
    "prior_loss_scale": false,
    "prior_loss_target": 100.0,
    "prior_loss_weight": 0.75,
    "prior_loss_weight_min": 0.1,
    "resolution": 512,
    "revision": 300,
    "sample_batch_size": 4,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": false,
    "save_ckpt_during": false,
    "save_ema": true,
    "save_embedding_every": 25,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": false,
    "save_lora_for_extra_net": false,
    "save_preview_every": 25,
    "save_safetensors": true,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": false,
    "scheduler": "DEISMultistep",
    "shuffle_tags": true,
    "snapshot": "",
    "split_loss": true,
    "src": "/home/user/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors",
    "stop_text_encoder": 0.75,
    "strict_tokens": false,
    "tf32_enable": false,
    "train_batch_size": 1,
    "train_imagic": false,
    "train_unet": true,
    "use_concepts": false,
    "use_ema": false,
    "use_lora": true,
    "use_lora_extended": false,
    "use_subdir": true,
    "v2": false
}

```

### 3. Provide logs

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```st
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on user user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
[+] xformers version 0.0.18 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments: --listen --enable-insecure-extension-access --no-half --xformers --api
2023-04-12 16:52:07.634999: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Loading weights [6ce0161689] from /home/user/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors
Creating model from config: /home/user/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 4.1s (load weights from disk: 0.3s, create model: 0.5s, apply weights to model: 0.5s, load VAE: 2.0s, move model to device: 0.7s).
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 11.0s (import torch: 2.8s, import gradio: 0.8s, import ldm: 0.4s, other imports: 1.0s, load scripts: 0.8s, load SD checkpoint: 4.2s, create ui: 0.3s, gradio launch: 0.4s, scripts app_started_callback: 0.2s).
Loading model from checkpoint.
Loading safetensors...
Pred and size are epsilon and 512, using config: /home/user/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/../configs/v1-training-default.yaml
v1 model loaded.
Trying to load: /home/user/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/../configs/v1-training-default.yaml
Converting unet...
Converting vae...
Converting text encoder...
Saving text_encoder
Saving tokenizer
Checkpoint successfully extracted to /home/user/stable-diffusion-webui/models/dreambooth/CilppyB/working
Restored system models.
Duration: 00:00:22
Updating scheduler name to: DDIM
Total images: 0
Total VRAM: 24
Total images: 0
Total VRAM: 24
Please check your dataset directories.
Duration: 00:00:00
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.14.0. Performing monkey-patch...
Pre-processing images: classifiers_0: : 0it [00:00, ?it/s]      We need a total of 30 class images.                                  
Pre-processing images: classifiers_0: : 0it [00:00, ?it/s]
Generating 30 class images for training...
Generating class images 0/30::   0%|                                                                          | 0/30 [00:00<?, ?it/s]Using scheduler: DEISMultistep
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  9.55it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  9.26it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  9.39it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  9.33it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  9.31it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  9.31it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  9.78it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 11.96it/s]
Generating class images 30/30:: 100%|████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 184230.04it/s]Restored system models.
Generated 30 new class images.
Generating class images 30/30:: 100%|████████████████████████████████████████████████████████████████| 30/30 [00:01<00:00, 26.52it/s]
Found 30 reg images.
Preparing dataset...
Init dataset!
Preparing Dataset (With Caching)
Bucket 0 (512, 512, 0) - Instance Images: 6 | Class Images: 30 | Max Examples/batch: 12                                              
Caching latents...: 100%|████████████████████████████████████████████████████████████████████████████| 36/36 [00:01<00:00, 21.45it/s]Saving cache!
Total Buckets 1 - Instance Images: 6 | Class Images: 30 | Max Examples/batch: 12                                                     
Caching latents...: 100%|████████████████████████████████████████████████████████████████████████████| 36/36 [00:01<00:00, 21.45it/s]
Total images / batch: 12, total examples: 12
Caching latents...: 100%|████████████████████████████████████████████████████████████████████████████| 36/36 [00:01<00:00, 21.36it/s]
Total dataset length (steps): 12
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 12
  Num Epochs = 150
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 112
  Total optimization steps = 900
  Total training steps = 1800
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: True, Optimizer: 8bit AdamW, Prec: bf16
  Gradient Checkpointing: False
  EMA: False
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 0.0001
  LoRA Text Encoder LR: 5e-05
  V2: False
Steps:  17%|███▎                | 300/1800 [01:50<09:10,  2.72it/s, inst_loss=0, loss=0.0209, lr=0.0001, prior_loss=0.0279, vram=7.2Model name: CilppyB:   0%|                                                                                      | 0/2 [00:00<?, ?it/s]
2023-04-12 16:57:57.866494: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-04-12 16:57:57.872090: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-04-12 16:57:57.872254: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-04-12 16:57:57.873180: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-04-12 16:57:57.873401: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-04-12 16:57:57.873540: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-04-12 16:57:57.873854: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-04-12 16:57:57.874042: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-04-12 16:57:57.874194: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-04-12 16:57:57.874339: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 16872 MB memory:  -> device: 0, name: NVIDIA RTX A5500, pci bus id: 0000:05:00.0, compute capability: 8.6
2023-04-12 16:57:58.233117: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [1]
         [[{{node Placeholder/_0}}]]
Saving /home/user/stable-diffusion-webui/models/dreambooth/CilppyB/logging/loss_plot_300.png
Saving /home/user/stable-diffusion-webui/models/dreambooth/CilppyB/logging/ram_plot_300.png
Cleanup log parse.
Generating Samples: 100%|██████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.45it/s]
OOM Detected, reducing batch/grad size to 0/1.██████████████████                                       | 1/2 [00:01<00:01,  1.07s/it]
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/home/user/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1169, in inner_loop
    noise_pred = unet(
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 495, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 631, in forward
    sample = upsample_block(
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 1813, in forward
    hidden_states = attn(
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 291, in forward
    attn_output = self.attn1(
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/cross_attention.py", line 205, in forward
    return self.processor(
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/cross_attention.py", line 442, in __call__
    query = attn.to_q(hidden_states)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/extensions/sd_dreambooth_extension/lora_diffusion/lora.py", line 34, in forward
    self.linear(input)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 307, in lora_Linear_forward
    return torch.nn.Linear_forward_before_lora(self, input)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 23.68 GiB total capacity; 5.81 GiB already allocated; 8.12 MiB free; 5.83 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:  17%|███▎                | 300/1800 [01:52<09:22,  2.66it/s, inst_loss=0, loss=0.0209, lr=0.0001, prior_loss=0.0279, vram=7.2]
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 727, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/home/user/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1371, in main
    return inner_loop()
  File "/home/user/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 117, in decorator
    raise RuntimeError("No executable batch size found, reached zero.")
RuntimeError: No executable batch size found, reached zero.
Restored system models.
Duration: 00:02:23

```

### 4. Environment

What OS?
Ubuntu 22.04.2 LTS
Python 3.10.6
cuda-11.8
NVIDIA Driver Version: 530.30.02
If Windows - WSL or native?
N/A
What GPU are you using?
NVIDIA RTX A5500

**Comment by ElliottLester** [comment]
@SilveRider76 
I'm not so sure looking at your logs.
You don't make it past step 1/3600 before your OOM
I can run until we generate the first samples, **our issues are not the same**.
At that point before sample generation I'm at 8.84G VRAM total which should fit on your card.
the only differences I can see between us are 
- Lora
- You loaded a VAE
- you updated to torch 2.0
- you have Gradient Checkpointing: True
- This is in your call stack and not in mine
``` 
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1798, in custom_forward
    return module(*inputs, return_dict=return_dict)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\transformer_2d.py", line 265, in forward
```


I'm saying there's something getting allocated for sample generation that's huge that's isn't being released preventing training from continuing.
Notice I make it to  Steps:  17%|███▎                | 300/1800 before the OOM 
at that point before sample generation I'm at 8.84G VRAM total which should fit on your card.
when we generate the sample i jump to over 23.68GB VRAM which is nuts.

**Comment by SilverRider76** [comment]
> @SilveRider76 I'm not so sure looking at your logs. You don't make it past step 1/3600 before your OOM I can run until we generate the first samples, **our issues are not the same**. At that point before sample generation I'm at 8.84G VRAM total which should fit on your card. the only differences I can see between us are
> 
> * Lora
> * You loaded a VAE
> * you updated to torch 2.0
> * you have Gradient Checkpointing: True
> * This is in your call stack and not in mine
> 
> ```
>     return super().apply(*args, **kwargs)  # type: ignore[misc]
>   File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 107, in forward
>     outputs = run_function(*args)
>   File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1798, in custom_forward
>     return module(*inputs, return_dict=return_dict)
>   File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "G:\ASD1111\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\transformer_2d.py", line 265, in forward
> ```
> 
> I'm saying there's something getting allocated for sample generation that's huge that's isn't being released preventing training from continuing. Notice I make it to Steps: 17%|███▎ | 300/1800 before the OOM at that point before sample generation I'm at 8.84G VRAM total when we generate the sample I jump to over 23.68GB VRAM which is nuts.

I understand, but I can tell you that I've try also with or withouth vae, with or withouth gradient checkpoint (and also with others parameters, ema on/off).

I've used yesterday the old version of dreambooth with Lora, and it work great.
The new version starting from 2 days ago stopped to work.
I've the sensation that the file "bitsandbytes\libbitsandbytes_cudaall.dll" is the cause, because is the only file with date changed from the installation.
But It's only my idea, nothing else.
Check the data of your  libbitsandbytes_cudaall.dll and let me know.

**Comment by ElliottLester** [comment]
hmm interesting ok can you go to 
stable-diffusion-webui/extensions/sd_dreambooth_extension
and run
``` 
git reflog --since=1.week.ago
```
that will tell me what commit was working for you.

**Comment by SilverRider76** [comment]
> hmm interesting ok can you go to stable-diffusion-webui/extensions/sd_dreambooth_extension and run
> 
> ```
> git reflog
> ```
> 
> that will tell me what commit was working for you. or do you have two installs one that is working and one that isn't?
> 
> ```
> commit 42dcf949f3d891b466e09e3bf9afe2b2c3937f0d
> Date:   Fri Feb 10 17:42:36 2023 -0600
> requirements.txt
> -bitsandbytes==0.37.0
> +bitsandbytes==0.35.4
> ```
> 
> reverted bits and bytes to 0.35.4 which was more than two days ago, however it does agree with me saying I have been unable to get it working since February.

I've two installation.
One is Kohya (the old one)
and the other is the last (updated)

Now I can't do your command, tomorrow I do it!
Thank you so much
and sorry for my horrible english ;) (I know that can seems rude, but I'm a nice person with english problem 😂)

**Comment by SilverRider76** [comment]
> hmm interesting ok can you go to stable-diffusion-webui/extensions/sd_dreambooth_extension and run
> 
> ```
> git reflog
> ```
> 
> that will tell me what commit was working for you. or do you have two installs one that is working and one that isn't?
> 
> ```
> commit 42dcf949f3d891b466e09e3bf9afe2b2c3937f0d
> Date:   Fri Feb 10 17:42:36 2023 -0600
> requirements.txt
> -bitsandbytes==0.37.0
> +bitsandbytes==0.35.4
> ```
> 
> reverted bits and bytes to 0.35.4 which was more than two days ago, however it does agree with me saying I have been unable to get it working since February.

the response about not working dreambooth to git reflog is:
926ae20 (HEAD ->main, tag: 1.0.14, origin/main, origin/head) HEAD@{0}: clone from https://github.com/d8ahazard/sd_dreambooth_extension.git

the working one is:
9c8c480 (HEAD ->master, tag: v21.4.2, origin/master, origin/head) HEAD@{0}: pull: Fast-foward 720dcd7 (tag: v21.4.1) HEAD@{1} clone from https://github.com/bmaltais/kohya_ss.git

I hope you can understand something 😂

**Comment by ElliottLester** [comment]
I am not interested in kohya's repo only this one.
Did you get d8ahazard's working at all?

**Comment by N0repi** [comment]
Just

> I think that we have all the same problem. I'm trying to train in Dreambooth (withouth Lora, using the classification images) and we got all the same error
> 
> I attach my log file PS: Windows 11 Pro, 32GB of Ram, Asus Dual nVidia 2060 with 12gb of ram last driver nVidia installed (yesterday) [Log2.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11221682/Log2.txt)

I had a occasionally had similar logs as yours when using Torch 2.0 . At my current torch version, I am able to complete training without an error... but as you mentioned, " Class Images: 0 " when defining an existing class dataset directory. It's very interesting to see that generating class images is working on Ell


@ElliottLester I'll test your issue later tonight. I'm using the dev branch. I understand that our issues are different, as your issue pertains to samples rather than class. Do pre-existing class images would properly on either of the commits you mentioned?

**Comment by ElliottLester** [comment]
I haven't had issues with "class images 0" even when restarting the same job.
I haven't tried to supply class images I have always generated them.

I didn't upgrade to torch 2.0 because then it's even more things are broken.
(do you have steps for upgrading to torch 2.0, not that I think it will solve my issue)

I didn't supply any commits.
I don't know what commit broke it if I did I would bisect it.

**Comment by SilverRider76** [comment]
> Just
> 
> > I think that we have all the same problem. I'm trying to train in Dreambooth (withouth Lora, using the classification images) and we got all the same error
> > I attach my log file PS: Windows 11 Pro, 32GB of Ram, Asus Dual nVidia 2060 with 12gb of ram last driver nVidia installed (yesterday) [Log2.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11221682/Log2.txt)
> 
> I had a occasionally had similar logs as yours when using Torch 2.0 . At my current torch version, I am able to complete training without an error... but as you mentioned, " Class Images: 0 " when defining an existing class dataset directory. It's very interesting to see that generating class images is working in the original post.

yes generating class is working like a charm if you use  "alone"
But when you try to train: class image:0 with a definited dataset directory.

Now I'm doing a clean install in another hard drive qnd see what happens.
(I'll try before updating torch and after updating torch to 2.0, so we can understand better)

**Comment by SilverRider76** [comment]
> I didn't upgrade to torch 2.0 because then even more things are broken. (do you have steps for upgrading to torch 2.0, not that I think it will solve my issue

I've followed this video:
https://youtu.be/pom3nQejaTs

**Comment by SilverRider76** [comment]
[log with ema on - withouth updating torch.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232471/log.with.ema.on.-.withouth.updating.torch.txt)
[log - withouth EMA - updated PIP - caching latens - no updated torch.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232472/log.-.withouth.EMA.-.updated.PIP.-.caching.latens.-.no.updated.torch.txt)
[log - updated all.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232473/log.-.updated.all.txt)
[log withouth ema - caching latens - withouth updating torch.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232474/log.withouth.ema.-.caching.latens.-.withouth.updating.torch.txt)

Ok, I've do everything, clean install.
I attach all my logs (the titles explain various trying)

Nothing change, always the same error:

926ae20 (HEAD -> main, tag: 1.0.14, origin/main, origin/HEAD) HEAD@{0}: clone: from https://github.com/d8ahazard/sd_dreambooth_extension

**Comment by ElliottLester** [comment]
> > > [log with ema on - withouth updating torch.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232471/log.with.ema.on.-.withouth.updating.torch.txt) [log - withouth EMA - updated PIP - caching latens - no updated torch.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232472/log.-.withouth.EMA.-.updated.PIP.-.caching.latens.-.no.updated.torch.txt) [log - updated all.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232473/log.-.updated.all.txt) [log withouth ema - caching latens - withouth updating torch.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232474/log.withouth.ema.-.caching.latens.-.withouth.updating.torch.txt)
> > > Ok, I've do everything, clean install. I attach all my logs (the titles explain various trying)
> > > Nothing change, always the same error:
> > > [926ae20](https://github.com/d8ahazard/sd_dreambooth_extension/commit/926ae204ef5de17efca2059c334b6098492a0641) (HEAD -> main, tag: 1.0.14, origin/main, origin/HEAD) HEAD@{0}: clone: from https://github.com/d8ahazard/sd_dreambooth_extension
> > 
> > 
> > ok in the logs for "Without EMA updated pip" it looks like you don't have the right version of Xformers you can get it from here [Xformers](https://github.com/facebookresearch/xformers/actions/runs/4566295779) I think you want this one -> windows-2019-py3.10-torch1.13.1+cu117 Then add it here `pip install {REPLACE WITH PATH TO YOUR UNZIPPED .whl file}`
> 
> I've already updated, look the log: updated all.txt
> 
> but, by the way, thank you anyway ;)

No you misunderstand,
in "all updated"  you are using **torch 2**
I'm saying go back to the state in "Without EMA updated pip" before you updated torch and install that version of xformers

**Comment by SilverRider76** [comment]
> > > > [log with ema on - withouth updating torch.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232471/log.with.ema.on.-.withouth.updating.torch.txt) [log - withouth EMA - updated PIP - caching latens - no updated torch.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232472/log.-.withouth.EMA.-.updated.PIP.-.caching.latens.-.no.updated.torch.txt) [log - updated all.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232473/log.-.updated.all.txt) [log withouth ema - caching latens - withouth updating torch.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232474/log.withouth.ema.-.caching.latens.-.withouth.updating.torch.txt)
> > > > Ok, I've do everything, clean install. I attach all my logs (the titles explain various trying)
> > > > Nothing change, always the same error:
> > > > [926ae20](https://github.com/d8ahazard/sd_dreambooth_extension/commit/926ae204ef5de17efca2059c334b6098492a0641) (HEAD -> main, tag: 1.0.14, origin/main, origin/HEAD) HEAD@{0}: clone: from https://github.com/d8ahazard/sd_dreambooth_extension
> > > 
> > > 
> > > ok in the logs for "Without EMA updated pip" it looks like you don't have the right version of Xformers you can get it from here [Xformers](https://github.com/facebookresearch/xformers/actions/runs/4566295779) I think you want this one -> windows-2019-py3.10-torch1.13.1+cu117 Then add it here `pip install {REPLACE WITH PATH TO YOUR UNZIPPED .whl file}`
> > 
> > 
> > I've already updated, look the log: updated all.txt
> > but, by the way, thank you anyway ;)
> 
> No you misunderstand, in "all updated" you are using **torch 2** I'm saying go back to the state in "Without EMA updated pip" before you updated torch and install that version of xformers

oh, ok, thank you (my english is still horrible also reading 😂)

**Comment by ElliottLester** [comment]
Updating to torch 2 give me this issue
https://github.com/d8ahazard/sd_dreambooth_extension/issues/1160

**Comment by SilverRider76** [comment]
> > > [log with ema on - withouth updating torch.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232471/log.with.ema.on.-.withouth.updating.torch.txt) [log - withouth EMA - updated PIP - caching latens - no updated torch.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232472/log.-.withouth.EMA.-.updated.PIP.-.caching.latens.-.no.updated.torch.txt) [log - updated all.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232473/log.-.updated.all.txt) [log withouth ema - caching latens - withouth updating torch.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/11232474/log.withouth.ema.-.caching.latens.-.withouth.updating.torch.txt)
> > > Ok, I've do everything, clean install. I attach all my logs (the titles explain various trying)
> > > Nothing change, always the same error:
> > > [926ae20](https://github.com/d8ahazard/sd_dreambooth_extension/commit/926ae204ef5de17efca2059c334b6098492a0641) (HEAD -> main, tag: 1.0.14, origin/main, origin/HEAD) HEAD@{0}: clone: from https://github.com/d8ahazard/sd_dreambooth_extension
> > 
> > 
> > ok in the logs for "Without EMA updated pip" it looks like you don't have the right version of Xformers you can get it from here [Xformers](https://github.com/facebookresearch/xformers/actions/runs/4566295779) I think you want this one -> windows-2019-py3.10-torch1.13.1+cu117 Then add it here `pip install {REPLACE WITH PATH TO YOUR UNZIPPED .whl file}`
> 
> I've already updated, look the log: updated all.txt
> 
> but, by the way, thank you anyway ;)

During installation it give me this error: 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.18 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchvision 0.15.1+cu118 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
open-clip-torch 2.7.0 requires protobuf==3.20.0, but you have protobuf 4.22.1 which is incompatible.
clean-fid 0.1.29 requires requests==2.25.1, but you have requests 2.28.2 which is incompatible.

after, I tryied to launch SD this error:
venv "G:\ASD1111\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Traceback (most recent call last):
  File "G:\ASD1111\stable-diffusion-webui\launch.py", line 355, in <module>
    prepare_environment()
  File "G:\ASD1111\stable-diffusion-webui\launch.py", line 260, in prepare_environment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "G:\ASD1111\stable-diffusion-webui\launch.py", line 121, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "G:\ASD1111\stable-diffusion-webui\launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "G:\ASD1111\stable-diffusion-webui\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

**Comment by ElliottLester** [comment]
you downloaded 
windows-2019-py3.10-**torch2.0.0**+cu118 
not 
windows-2019-py3.10-**torch1.13.1**+cu117

**Comment by SilverRider76** [comment]
> you downloaded windows-2019-py3.10-**torch2.0.0**+cu118
> 
> get this one -> windows-2019-py3.10-**torch1.13.1**+cu117

I downloaded: windows-2019-py3.10-torch1.12.1+cu116.zip
Inside the zip there is: xformers-0.0.18-cp310-cp310-win_amd64.whl

**Comment by N0repi** [comment]
> I haven't had issues with "class images 0" even when restarting the same job. I haven't tried to supply class images I have always generated them.
> 
> I didn't upgrade to torch 2.0 because then even more things are broken. (do you have steps for upgrading to torch 2.0, not that I think it will solve my issue)
> 
> ~I didn't supply any commits.~ ~I don't know what commit broke it if I did I would bisect it.~ tag 1.0.12 seems to work as expected 10.4GB for training, 22.6GB after the first sample. tag 1.0.13 seems to work as expected 10.4GB for training, 20.6GB after the first sample. tag 1.0.14 seems to work as expected 10.4GB for training, 22.6GB after the first sample.
> 
> ok that's weird going through the checkpoints up to head and it works now?


I apologize for my delayed reply. I wasn't able to test your issue last night. Though, it seems like it's working for you now, right?

I used the following command to install Torch 2.0 
pip3 install clean-fid numba numpy torch==2.0.0+cu118 torchvision --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu118

If you get errors after installing Torch 2.0, you may need to remove xformer's dependencies.

This allowed me to use the command line argument "--opt-sdp-attention" in SD. However, I have never been able to get Dreambooth to train using Torch 2.0 . Please let me know if you get it working at some point.

**Comment by N0repi** [comment]
> yes generating class is working like a charm if you use "alone" But when you try to train: class image:0 with a definited dataset directory.

What do you mean by "alone"?

> open-clip-torch 2.7.0 requires protobuf==3.20.0, but you have protobuf 4.22.1 which is incompatible.
clean-fid 0.1.29 requires requests==2.25.1, but you have requests 2.28.2 which is incompatible.

I get these "incompatible messages" about protobuf and requests every time I run ' pip install -r requirements.txt ' in my venv in the root SD webui folder. I'm not sure if that's normal, but I have 4 SD installations w/ DreamBooth that all get those messages.

Regarding Torch 2.0, for cuda-11.8, you need to use cudnn 8.7 . I think you can use cuda-11.7 with cudnn 8.5, but I haven't tested that.

**Comment by ElliottLester** [comment]
> > I haven't had issues with "class images 0" even when restarting the same job. I haven't tried to supply class images I have always generated them.
> > I didn't upgrade to torch 2.0 because then even more things are broken. (do you have steps for upgrading to torch 2.0, not that I think it will solve my issue)
> > ~I didn't supply any commits.~ ~I don't know what commit broke it if I did I would bisect it.~ tag 1.0.12 seems to work as expected 10.4GB for training, 22.6GB after the first sample. tag 1.0.13 seems to work as expected 10.4GB for training, 20.6GB after the first sample. tag 1.0.14 seems to work as expected 10.4GB for training, 22.6GB after the first sample.
> > ok that's weird going through the checkpoints up to head and it works now?
> 
> I apologize for my delayed reply. I wasn't able to test your issue last night. Though, it seems like it's working for you now, right?
> 
> I used the following command to install Torch 2.0 pip3 install clean-fid numba numpy torch==2.0.0+cu118 torchvision --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu118
> 
> If you get errors after installing Torch 2.0, you may need to remove xformer's dependencies.
> 
> This allowed me to use the command line argument "--opt-sdp-attention" in SD. However, I have never been able to get Dreambooth to train using Torch 2.0 . Please let me know if you get it working at some point.

tag 1.0.14 seems to work as expected with torch 1.13.1_+c117
10.4GB for training, 22.6GB after the first sample.

I did get dream booth training with torch 2 but I run out of VRam again after the first sample we are still over 20GB but dream booth is reporting <10 GB

**Comment by SilverRider76** [comment]
Ok, it seems working now (me too).
My Steps:

1) Clean Install of Automatic1111 V1.7.0
2) Updated Pip 
3) I've installed Dreambooth using: `git clone https://github.com/d8ahazard/sd_dreambooth_extension.git` (and **NOT** from extension tab on Automat1111)
4) Updated [[windows-2019-py3.10-torch1.13.1+cu117](https://github.com/facebookresearch/xformers/suites/11921394063/artifacts/624798156)] using `pip install  xformers-0.0.18-cp310-cp310-win_amd64.whl`
5) Downgraded to old Gradio using: `git checkout a9fed7c364061ae6efb37f797b6b522cb3cf7aa2`

(nVidia yesterday have pulled out new driver and I've installed)

**Comment by N0repi** [comment]
> 

Thanks for the shell script! The info about dynamo is good to know. I'm still getting the following error when training in DB w/ torch 2.0, even with 'export TORCHDYNAMO_DISABLE=1'. It always occurs right after latents are cached. I'll dive into fixing the problem tomorrow. I'm just posting this here in the event that anyone comes across this issue later.

```st
Steps:   0%|                                                              | 0/75000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/NAS/AI-ML/SD/SD_newer/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 730, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/mnt/NAS/AI-ML/SD/SD_newer/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1456, in main
    return inner_loop()
  File "/mnt/NAS/AI-ML/SD/SD_newer/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/mnt/NAS/AI-ML/SD/SD_newer/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1278, in inner_loop
    accelerator.backward(loss)
  File "/mnt/NAS/AI-ML/SD/SD_newer/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1683, in backward
    loss.backward(**kwargs)
  File "/mnt/NAS/AI-ML/SD/SD_newer/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/mnt/NAS/AI-ML/SD/SD_newer/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by kelvie** [comment]
I'm also seeing this. It seems I can have a batch size of 4 until the first sample generation, then it goes OOM and it doesn't recover the VRAM, and I have to restart the whole webui.

**Comment by manugarri** [comment]
bump
