### ISSUE TITLE
Graident checkpointing causes crash: assert "source" in options and options["source"] is not None

### ISSUE THREAD

**Issue by butchmarshall** [d8ahazard/sd_dreambooth_extension#1192]
### 1. Please find the following lines in the console and paste them below.

```
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed accelerate-0.18.0 fastapi-0.94.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 requests-2.28.2 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.18 installed.
[+] torch version 2.0.0 installed.
[+] torchvision version 0.15.1 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.
```

### 2. Describe the bug

When checking the  `Gradient checkpointing` option after clicking Train i receive a crash message

### 3. Provide logs

```st
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121_nomatmul
python setup.py install
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121_nomatmul
python setup.py install
Exception importing 8bit AdamW: 
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs aboveto fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
Traceback (most recent call last):
  File "/opt/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/optimization.py", line 518, in get_optimizer
    from bitsandbytes.optim import AdamW8bit
  File "/home/butch/.local/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/home/butch/.local/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/home/butch/.local/lib/python3.10/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/butch/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 118, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs aboveto fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues

        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs aboveto fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
WARNING: Using default optimizer (AdamW from Torch)
Found 30 reg images.
Preparing dataset...
Init dataset!
Preparing Dataset (With Caching)
Caching latents...:   0%|                                                                              | 0/36 [00:00<?, ?it/s]Loading cached latents...
Bucket 0 (512, 512, 0) - Instance Images: 6 | Class Images: 30 | Max Examples/batch: 12                                       
Total Buckets 1 - Instance Images: 6 | Class Images: 30 | Max Examples/batch: 12                                              
Caching latents...: 100%|███████████████████████████████████████████████████████████████████| 36/36 [00:00<00:00, 4911.84it/s]
Total images / batch: 12, total examples: 12
Caching latents...: 100%|███████████████████████████████████████████████████████████████████| 36/36 [00:00<00:00, 4878.04it/s]
Total dataset length (steps): 12
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 12
  Num Epochs = 1
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 1
  Total optimization steps = 6
  Total training steps = 12
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Optimizer: Torch AdamW, Prec: bf16
  Gradient Checkpointing: True
  EMA: True
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 2e-06
  V2: False
Steps:   0%|                                                                                           | 0/12 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/opt/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 727, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/opt/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1371, in main
    return inner_loop()
  File "/opt/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/opt/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1169, in inner_loop
    noise_pred = unet(
  File "/home/butch/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/butch/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 495, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/butch/.local/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/butch/.local/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 685, in forward
    sample, res_samples = downsample_block(
  File "/home/butch/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/butch/.local/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 858, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(create_custom_forward(resnet), hidden_states, temb)
  File "/home/butch/.local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/butch/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/butch/.local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 81, in forward
    ctx.fwd_cpu_state = torch.get_rng_state()
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 342, in wrapper
    return inner_fn(self, inst)
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 965, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 474, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/variables/torch.py", line 368, in call_function
    return wrap_fx_proxy(
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 754, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/home/butch/.local/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 812, in wrap_fx_proxy_cls
    assert "source" in options and options["source"] is not None
AssertionError: 

from user code:
   File "/home/butch/.local/lib/python3.10/site-packages/torch/random.py", line 23, in get_rng_state
    return default_generator.get_state()

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

```

### 4. Environment

What OS? Ubuntu 22.04
What GPU are you using? MSI gaming Trio 4090

**Comment by Vector-Cross** [comment]
what if do not check?

**Comment by dioscuroi** [comment]
This error seems to be related to the following issue:
https://github.com/pytorch/pytorch/issues/97077#issuecomment-1480408700

Any suggestion how to fix the error?

**Comment by Zhengbaibai** [comment]
> This error seems to be related to the following issue: [pytorch/pytorch#97077 (comment)](https://github.com/pytorch/pytorch/issues/97077#issuecomment-1480408700)
> 
> Any suggestion how to fix the error?

it works for me
https://github.com/d8ahazard/sd_dreambooth_extension/pull/1186#issuecomment-1518694203

**Comment by dioscuroi** [comment]
> > This error seems to be related to the following issue: [pytorch/pytorch#97077 (comment)](https://github.com/pytorch/pytorch/issues/97077#issuecomment-1480408700)
> > Any suggestion how to fix the error?
> 
> it works for me [#1186 (comment)](https://github.com/d8ahazard/sd_dreambooth_extension/pull/1186#issuecomment-1518694203)

It works like a charm! Thank you!!  🎉
