### ISSUE TITLE
Apple Silicon GPU seems to not be recognized. 

### ISSUE THREAD

**Issue by armaanhammer** [d8ahazard/sd_dreambooth_extension#1221]
### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Python 3.10.10 (main, Apr  9 2023, 20:06:33) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Commit hash: 1e30ae895e487b1b4b81033db14863c702d26268
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
[!] xformers NOT installed.
[+] torch version 2.0.1 installed.
[+] torchvision version 0.15.2 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################
```

### 2. Describe the bug

In brief, pressing [Train] within the Dreambooth extension yields this error:

`Exception initializing accelerator: fp16 mixed precision requires a GPU`

In detail: I am on a Apple Macbook Pro with an M1 Max with 32GB ram, running MacOS 13.3.1. I created a fresh install of Stable Diffusion web UI using `[install-web-ui-1.1.1-rc-arm.tar.xz](https://github.com/brkirch/stable-diffusion-webui/releases/download/v1.1.1-RC/install-web-ui-1.1.1-rc-arm.tar.xz)` in this release: https://github.com/brkirch/stable-diffusion-webui/releases/tag/v1.1.1-RC . After installing Stable Diffusion web UI, I copied the v1.5 Stable Diffusion model into the correct directory, started the webUI, and installed the Dreambooth extension through the webUI. I then attempted to train a model and encountered the above error.

**Screenshots/Config**
db_config.json file:

```
{
    "adamw_weight_decay": 0.01,
    "adaptation_beta1": 0,
    "adaptation_beta2": 0,
    "adaptation_d0": 1e-08,
    "adaptation_eps": 1e-08,
    "attention": "default",
    "cache_latents": true,
    "clip_skip": 1,
    "concepts_list": [
        {
            "class_data_dir": "",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 40,
            "class_negative_prompt": "",
            "class_prompt": "person",
            "class_token": "",
            "instance_data_dir": "/Users/armaan/Workspace/install_location/stable-diffusion-webui/_training/Sups-first-run-for-Stable-Diffusion",
            "instance_prompt": "supsfrstrn",
            "instance_token": "",
            "is_valid": true,
            "n_save_sample": 1,
            "num_class_images_per": 0,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 20,
            "save_sample_negative_prompt": "",
            "save_sample_prompt": "",
            "save_sample_template": ""
        }
    ],
    "concepts_path": "",
    "custom_model_name": "",
    "noise_scheduler": "DDPM",
    "deterministic": false,
    "ema_predict": false,
    "epoch": 0,
    "epoch_pause_frequency": 0,
    "epoch_pause_time": 0,
    "freeze_clip_normalization": false,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": false,
    "gradient_set_to_none": true,
    "graph_smoothing": 50,
    "half_model": false,
    "train_unfrozen": false,
    "has_ema": false,
    "hflip": false,
    "infer_ema": false,
    "initial_revision": 0,
    "learning_rate": 2e-06,
    "learning_rate_min": 1e-06,
    "lifetime_revision": 0,
    "lora_learning_rate": 0.0001,
    "lora_model_name": null,
    "lora_unet_rank": 4,
    "lora_txt_rank": 4,
    "lora_txt_learning_rate": 5e-05,
    "lora_txt_weight": 1,
    "lora_weight": 1,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "constant_with_warmup",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "mixed_precision": "fp16",
    "model_name": "supsfrstrn",
    "model_dir": "/Users/armaan/Workspace/install_location/stable-diffusion-webui/models/dreambooth/supsfrstrn",
    "model_path": "/Users/armaan/Workspace/install_location/stable-diffusion-webui/models/dreambooth/supsfrstrn",
    "num_train_epochs": 100,
    "offset_noise": 0,
    "optimizer": "8bit AdamW",
    "pad_tokens": true,
    "pretrained_model_name_or_path": "/Users/armaan/Workspace/install_location/stable-diffusion-webui/models/dreambooth/supsfrstrn/working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_scale": false,
    "prior_loss_target": 100.0,
    "prior_loss_weight": 0.75,
    "prior_loss_weight_min": 0.1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 1,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": false,
    "save_ckpt_during": false,
    "save_ema": true,
    "save_embedding_every": 25,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": false,
    "save_lora_for_extra_net": false,
    "save_preview_every": 5,
    "save_safetensors": true,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": false,
    "scheduler": "DEISMultistep",
    "shuffle_tags": true,
    "snapshot": "",
    "split_loss": true,
    "src": "/Users/armaan/Workspace/install_location/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt",
    "stop_text_encoder": 0.75,
    "strict_tokens": false,
    "tf32_enable": false,
    "train_batch_size": 1,
    "train_imagic": false,
    "train_unet": true,
    "use_concepts": false,
    "use_ema": false,
    "use_lora": false,
    "use_lora_extended": false,
    "use_subdir": true,
    "v2": false
}
```

### 3. Provide logs
```st
(base) ➜  ~ cd '/Users/armaan/Workspace/install_location/stable-diffusion-webui';./webui.sh --autolaunch;exit

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on armaan user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.10 (main, Apr  9 2023, 20:06:33) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Commit hash: 1e30ae895e487b1b4b81033db14863c702d26268
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
[!] xformers NOT installed.
[+] torch version 2.0.1 installed.
[+] torchvision version 0.15.2 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments: --autolaunch --skip-torch-cuda-test --skip-install --no-download-sd-model --no-half-vae --upcast-sampling --opt-sub-quad-attention --use-cpu interrogate
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [cc6cb27103] from /Users/armaan/Workspace/install_location/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
Creating model from config: /Users/armaan/Workspace/install_location/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying sub-quadratic cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 2.4s (load weights from disk: 0.6s, create model: 0.5s, apply weights to model: 0.4s, apply half(): 0.3s, move model to device: 0.6s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 22.5s (import torch: 17.5s, import gradio: 0.3s, import ldm: 0.3s, other imports: 0.5s, load scripts: 0.7s, load SD checkpoint: 2.5s, create ui: 0.5s, gradio launch: 0.2s).
Loading model from checkpoint.
Loading ckpt...
Pred and size are epsilon and 512, using config: /Users/armaan/Workspace/install_location/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/../configs/v1-training-default.yaml
v1 model loaded.
Trying to load: /Users/armaan/Workspace/install_location/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/../configs/v1-training-default.yaml
Converting unet...
Converting vae...
Converting text encoder...
Downloading pytorch_model.bin: 100%|███████████████████████████████████████████████| 1.71G/1.71G [03:13<00:00, 8.82MB/s]
Saving text_encoder
Saving tokenizer
Checkpoint successfully extracted to /Users/armaan/Workspace/install_location/stable-diffusion-webui/models/dreambooth/supsfrstrn/working
Restored system models.
Duration: 00:03:31
Updating scheduler name to: DDIM
Total images: 0
Please check your dataset directories.
Duration: 00:00:00
Replacing flash attention in config to default
Replacing flash attention in config to default
Replacing flash attention in config to default
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.14.0. Performing monkey-patch...
Exception initializing accelerator: fp16 mixed precision requires a GPU
Restored system models.
Duration: 00:00:01
```

### 4. Environment

What OS? **MacOS 13.3.1**

If Windows - WSL or native? **n/a**

What GPU are you using? **Apple Silicon M1 Max**

**Comment by armaanhammer** [comment]
Out of curiosity, I closed the webUI, then changed this line in `webui-macos-env.sh`: 
```
export COMMANDLINE_ARGS="--skip-torch-cuda-test --skip-install --no-download-sd-model --no-half-vae --upcast-sampling --opt-sub-quad-attention --use-cpu interrogate"
```
and removed ` --use-cpu interrogate`. 

After rerunning the webUI, and attempting to Train again, I got this output:

```
(base) ➜  ~ cd '/Users/armaan/Workspace/install_location/stable-diffusion-webui';./webui.sh --autolaunch;exit

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on armaan user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.10 (main, Apr  9 2023, 20:06:33) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Commit hash: 1e30ae895e487b1b4b81033db14863c702d26268
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
[!] xformers NOT installed.
[+] torch version 2.0.1 installed.
[+] torchvision version 0.15.2 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments: --autolaunch --skip-torch-cuda-test --skip-install --no-download-sd-model --no-half-vae --upcast-sampling --opt-sub-quad-attention
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [cc6cb27103] from /Users/armaan/Workspace/install_location/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
Creating model from config: /Users/armaan/Workspace/install_location/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying sub-quadratic cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 2.5s (load weights from disk: 0.7s, create model: 0.5s, apply weights to model: 0.5s, apply half(): 0.3s, move model to device: 0.5s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 7.7s (import torch: 2.6s, import gradio: 0.3s, import ldm: 0.3s, other imports: 0.5s, load scripts: 0.7s, load SD checkpoint: 2.7s, create ui: 0.5s, gradio launch: 0.2s).
Total images: 22
Largest prime: 11
Best factors: (2, 11)
Wizard results:<br>Num Epochs: 150<br>Num instance images per class image: 5
Replacing flash attention in config to default
Replacing flash attention in config to default
Exception loading config: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/armaan/Workspace/install_location/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 390, in from_file
    config_dict = json.load(openfile)
  File "/Users/armaan/Workspace/install_location/stable-diffusion-webui/python/3.10.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Users/armaan/Workspace/install_location/stable-diffusion-webui/python/3.10.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/armaan/Workspace/install_location/stable-diffusion-webui/python/3.10.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/armaan/Workspace/install_location/stable-diffusion-webui/python/3.10.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Duration: 00:00:00
Error completing request
Arguments: ('supsfrstrn', 'Native Diffusers') {}
Traceback (most recent call last):
  File "/Users/armaan/Workspace/install_location/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/utils.py", line 190, in f
    res = func(*args, **kwargs)
  File "/Users/armaan/Workspace/install_location/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 681, in start_training
    if config.pretrained_vae_name_or_path == "":
AttributeError: 'NoneType' object has no attribute 'pretrained_vae_name_or_path'

Traceback (most recent call last):
  File "/Users/armaan/Workspace/install_location/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/armaan/Workspace/install_location/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1302, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/armaan/Workspace/install_location/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1206, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/Users/armaan/Workspace/install_location/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1181, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 3).
Wanted outputs:
    [dropdown, html, html, gallery, html]
Received outputs:
    [None, "", "<div class='error'>AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;pretrained_vae_name_or_path&#x27;</div>"]
```

**Comment by benrugg** [comment]
+1 I'm having this same error on a similar Mac M1, same version of Mac OS, 64 gb ram

**Comment by benrugg** [comment]
Actually, I was able to get it working by doing this:
- change optimizer to `Lion`
- change mixed precision to `no`
- restart automatic1111 (save settings first, then refresh page and load settings again)

**Comment by 4ld3v** [comment]
> Actually, I was able to get it working by doing this:
> 
> * change optimizer to `Lion`
> * change mixed precision to `no`
> * restart automatic1111 (save settings first, then refresh page and load settings again)

@benrugg: Can you create a short howto?I tried it with your settings, but I still get a "PyTorch was not compiled with CUDA support" exception.

**Comment by benrugg** [comment]
@4ld3v, oh man, I honestly have no idea anymore how I fumbled my way through these settings. For what it's worth, I think the error about PyTorch/CUDA is normal on a mac, because Mac's don't have Nvidia gpu's (and CUDA is for Nvidia). If you're seeing any other errors, those would probably be the ones to track down.

**Comment by 4ld3v** [comment]
> @4ld3v, oh man, I honestly have no idea anymore how I fumbled my way through these settings. For what it's worth, I think the error about PyTorch/CUDA is normal on a mac, because Mac's don't have Nvidia gpu's (and CUDA is for Nvidia). If you're seeing any other errors, those would probably be the ones to track down.

thanks for your response Ben. Got ya, the thing is that when the exception is thrown, the training process will end. I will fiddle around and try some other settings.
