### ISSUE TITLE
CUDA out of memory after generating checkpoint. Memory not released correctly?

### ISSUE THREAD

**Issue by ReflectionRip** [d8ahazard/sd_dreambooth_extension#173]
**Have you read the Readme?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

Dreambooth revision is 5d8a331a142abe15516bec8f9a069241ed28c239
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.

**Describe the bug**
After saving a checkpoint and the training continues, CUDA out of memory error is displayed. It looks like the memory is not released.

**Provide logs**
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
 Scheduler Loaded
 Allocated: 0.6GB
 Reserved: 0.7GB

Steps:  83%|█████████████████████████████████████████▋        | 500/600 [07:09<01:19,  1.26it/s, loss=0.00814, lr=5e-6]Successfully trained model for a total of 2000 steps, converting to ckpt.
[*] Weights saved at D:\StableDiffusion\stable-diffusion-webui\models\dreambooth\yuzuyu
 Exception while training: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 12.00 GiB total capacity; 10.42 GiB already allocated; 0 bytes free; 10.97 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 9.7GB
 Reserved: 11.0GB

Traceback (most recent call last):
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 985, in main
    accelerator.backward(loss)
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 1188, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply    return user_fn(self, *args)
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 146, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 12.00 GiB total capacity; 10.42 GiB already allocated; 0 bytes free; 10.97 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Exception while training: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 12.00 GiB total capacity; 11.05 GiB already allocated; 0 bytes free; 11.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 9.5GB
 Reserved: 11.3GB

**Environment**
What OS?
Windows 10
If Windows - WSL or native?
Native
What GPU are you using?
Nvidia GeForce RTX 3060

**Comment by ReflectionRip** [comment]
There is a workaround for this. Just set 'Save a checkpoint every N steps, 0 to disable' to 0.

**Comment by ReflectionRip** [comment]
This also only happens for me if I don't use xformers

**Comment by d8ahazard** [comment]
I *think* I maybe fixed this with commit f946126

Please give a try and let me know. Thanks.

**Comment by aetherwu** [comment]
> There is a workaround for this. Just set 'Save a checkpoint every N steps, 0 to disable' to 0.

It works for me.
