### ISSUE TITLE
After updating I can no longer train, CUDA OOM every time

### ISSUE THREAD

**Issue by Jonseed** [d8ahazard/sd_dreambooth_extension#190]
**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

```
Dreambooth revision is 7e184a6cb95df776c2a1d86eea29321bff999899
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
```

**Describe the bug**
Nothing that I try today will train. I've tried changing all the settings. The only thing that I can tell that is different is that we are on diffusers 0.7.2 now, and I think before we were on 0.8.0.dev0 when it was working. Could the diffusers version be the difference? How do I go back to 0.8.0.dev0 to test it?

**Provide logs**
No crash, just CUDA OOM.

**Environment**
What OS? Windows
If Windows - WSL or native? native
What GPU are you using? 3060 12GB

**Comment by d8ahazard** [comment]
Are you using xformers?

**Comment by Jonseed** [comment]
Yes. Should I turn that off?

**Comment by Jonseed** [comment]
It was working before with it on.

**Comment by d8ahazard** [comment]
Do a pull now, I've hacked the "official" diffusers version to use xformers.

**Comment by Jonseed** [comment]
I can confirm that training works for me on 0.8.0.dev0, but **_NOT_** on 0.7.2 diffusers. On 0.7.2 I get OOM every time, no matter the settings. I have not tried updating yet to use your hacked version...

**Comment by d8ahazard** [comment]
I believe you. The hacked version does a check for xformers, and if they're installed, sets cross-attention to use it. It's a minor change, but probably the one we need.

**Comment by stysmmaker** [comment]
Should we respect the `--xformers` flag by checking `shared.xformers_available` as well?

**Comment by d8ahazard** [comment]
> Should we respect the `--xformers` flag by checking `shared.xformers_available` as well?

I mean...we can do whatever we want, really, now that we're monkey-patching the class ourselves. I don't think it's a bad idea.

**Comment by d8ahazard** [comment]
> Should we respect the `--xformers` flag by checking `shared.xformers_available` as well?

Added with 20eec77

**Comment by Jonseed** [comment]
I think you mean d4c0312d22033fd0550e0ab51f08789b56966138

**Comment by Jonseed** [comment]
Ok, testing your hacked official 0.7.2 diffusers to use xformers, and it started training fine. But when it got to generating the first preview at 100 steps I got this error and training stopped:

```
Exception while training: Pipeline <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> expected {'scheduler', 'unet', 'tokenizer', 'text_encoder', 'safety_checker', 'feature_extractor', 'vae'}, but only {'scheduler', 'unet', 'tokenizer', 'text_encoder', 'feature_extractor', 'vae'} were passed.
 Allocated: 5.5GB
 Reserved: 9.2GB

Traceback (most recent call last):
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1039, in main
    save_weights(lifetime_step, save_model, save_img)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 887, in save_weights
    pipeline = StableDiffusionPipeline.from_pretrained(
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipeline_utils.py", line 642, in from_pretrained
    raise ValueError(
ValueError: Pipeline <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> expected {'scheduler', 'unet', 'tokenizer', 'text_encoder', 'safety_checker', 'feature_extractor', 'vae'}, but only {'scheduler', 'unet', 'tokenizer', 'text_encoder', 'feature_extractor', 'vae'} were passed.
```

Is the safety_checker missing?

**Comment by Jonseed** [comment]
Switching back to diffusers 0.8.0.dev0 works again, including generating previews.

**Comment by d8ahazard** [comment]
Fixed the safety checker issue with 4647d85. Problem is that the dev0 version has an optional param to make it None, "official" doesn't.

**Comment by Jonseed** [comment]
Ok, it works now, but it does give a long safety checker warning in the terminal each time it generates a preview.

**Comment by Jonseed** [comment]
Since it is working now, I'll close this.

**Comment by Jonseed** [comment]
Actually, @d8ahazard , now that it completed training, it did have a problem at the very end of a training session. It did not save a ckpt file properly, but gave this error:

```
Exception saving checkpoint/model: [Errno 13] Permission denied: 'F:\\repos\\auto111\\stable-diffusion-webui\\models\\dreambooth\\training1\\working\\text_encoder\\pytorch_model.bin'
Traceback (most recent call last):
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 905, in save_weights
    pipeline.save_pretrained(args.working_dir)
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipeline_utils.py", line 202, in save_pretrained
    save_method(os.path.join(save_directory, pipeline_component_name))
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 1563, in save_pretrained
    save_function(shard, os.path.join(save_directory, shard_file))
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'F:\\repos\\auto111\\stable-diffusion-webui\\models\\dreambooth\\training1\\working\\text_encoder\\pytorch_model.bin'
```

Does this have something to do with the different diffusers version too? I didn't have a permissionerror with the other version when saving the ckpt file.

**Comment by Jonseed** [comment]
@d8ahazard any idea why diffusers 0.7.2 would give me this permission error when saving the ckpt and 0.8.0.dev0 does not?

**Comment by d8ahazard** [comment]
The permission error should be fixed with the latest commit(s). Please update and confirm/deny and close if applicable. :P

**Comment by d8ahazard** [comment]
I've also shuushed the warning about the safety checker.
