### ISSUE TITLE
Issue with mixed precision at the start of training

### ISSUE THREAD

**Issue by vgaggia** [d8ahazard/sd_dreambooth_extension#216]
**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**
loading Dreambooth reqs from G:\Auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt
Checking Dreambooth requirements.
Checking torch and torchvision versions
Dreambooth revision is 4684f0faea19c243216eac2278a42fcfcbbd756b
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Copying 8Bit Adam files for Windows.

When trying to train without mixed precision i'm getting this error:

Traceback (most recent call last):
  File "G:\Auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 923, in main
    accelerator.backward(loss)
  File "G:\Auto\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 884, in backward
    loss.backward(**kwargs)
  File "G:\Auto\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "G:\Auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "G:\Auto\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "G:\Auto\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "G:\Auto\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument

**Environment**
Windows 11
Native Windows
RTX 3090

**Comment by d8ahazard** [comment]
Either use fp16 or disable the xformers flag.

**Comment by vgaggia** [comment]
I'm getting the same issue without the xformers flag

**Comment by d8ahazard** [comment]
> Diffusers version is 0.8.0.dev0.

I see this, which makes me think you at least need to do an update and restart SD WebUI. Should be using diffusers version 0.7.2.

That probably won't fix the issue though.

What might is updating your drivers via installing the CUDA toolkit. Give this a go:

https://developer.nvidia.com/cuda-11-6-0-download-archive

**Comment by vgaggia** [comment]
I realized what it is now, even though i've been updating the extension, i've been doing it via git pull and the webui, i noticed my requirements only had about 7-8 lines in there, so i checked the repo on github and there it is, all the correct requirements, after copy and pasting those in it's working now, the cuda wasn't needed.

**Comment by vgaggia** [comment]
So unfortunately now, this has caused a new issue, the amount of vram i'm using is way more, before i could train @ 706 and only be using 18gb of vram, decided to test mixed precision again and its still running out of memory, if i turn all the memory saving options on i just barely run under 24gb of vram @ 640, any idea why updating would make it consume way more vram?

**Comment by vgaggia** [comment]
Ok, so more issues, i realized when i was updating the repo i was getting some commit issue since i changed requirements, i managed to update the repo now by deleting req.txt, anyways, i see the new layout of dreambooth and all, but now i'm just getting:
 
__getitem__
    example["instance_prompt"] = self.text_getter.create_text(instance_prompt,
  File "G:\Auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 41, in create_text
    if shared.opts.tag_drop_out != 0:
  File "G:\Auto\stable-diffusion-webui\modules\shared.py", line 433, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'tag_drop_out'

**Comment by d8ahazard** [comment]
> Ok, so more issues, i realized when i was updating the repo i was getting some commit issue since i changed requirements, i managed to update the repo now by deleting req.txt, anyways, i see the new layout of dreambooth and all, but now i'm just getting:
> 
> **getitem** example["instance_prompt"] = self.text_getter.create_text(instance_prompt, File "G:\Auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 41, in create_text if shared.opts.tag_drop_out != 0: File "G:\Auto\stable-diffusion-webui\modules\shared.py", line 433, in **getattr** return super(Options, self).**getattribute**(item) AttributeError: 'Options' object has no attribute 'tag_drop_out'
> 
> I'm using [filewords] as the instance prompt
> 
> Let me know if you want me to close this issue and start a new one rather as well.

Please do. This issue is related to an old version of the SD-WebUI.

**Comment by vgaggia** [comment]
Using a fresh install fixed it with the new webui-user-dreambooth.bat you made
