### ISSUE TITLE
downloaded linux versions of a few files on a windows install (I think)

### ISSUE THREAD

**Issue by differentprogramming** [d8ahazard/sd_dreambooth_extension#225]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

By the way I tried this both in anaconda and in the global python environment and got the same result.
`
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is 4152085e974bd64f402cf13393e694acf2ccef78
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Copying 8Bit Adam files for Windows.

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**
When I start training I get a popup saying that libbitsandbyte_cpu.so isn't a windows file. 
 and there's a similar complaint in the log that 8bitadam is not a valid win32 application

I get an error a bunch of times then it gives up

**Provide logs**

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary E:\stable\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
Exception importing 8bit adam: [WinError 193] %1 is not a valid Win32 application
 Scheduler Loaded
 Allocated: 0.3GB
 Reserved: 0.3GB

***** Running training *****
  Num examples = 27
  Num batches each epoch = 27
  Num Epochs = 97
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 2600
Steps:   0%|                                                                                  | 0/2600 [00:00<?, ?it/s] Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 4.2GB
 Reserved: 5.6GB

Traceback (most recent call last):
  File "E:\stable\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 975, in main
    accelerator.backward(loss)
  File "E:\stable\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 1190, in backward
    loss.backward(**kwargs)
  File "E:\stable\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "E:\stable\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "E:\stable\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "E:\stable\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 146, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "E:\stable\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "E:\stable\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "E:\stable\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "E:\stable\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 4.2GB
 Reserved: 5.6GB

It repeats the error over and over then after that:

CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 CLEANUP:
 Allocated: 4.2GB
 Reserved: 5.6GB

 Cleanup Complete.
 Allocated: 4.2GB
 Reserved: 5.6GB

Steps:   0%|                                                                                  | 0/2600 [01:26<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Memory output: {'VRAM cleared.': '0.0/0.0GB', 'Loaded model.': '0.0/0.0GB', 'Scheduler Loaded': '0.3/0.3GB', 'Exception while training: CUDA error: invalid argument\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.': '4.2/5.6GB', 'CLEANUP: ': '4.2/5.6GB', 'Cleanup Complete.': '4.2/5.6GB', 'Training completed, reloading SD Model.': '0.0/0.0GB'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 0

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS?
Windows 10 64 bit

If Windows - WSL or native?
native

What GPU are you using?
3060

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by Art4DD** [comment]
I also get an error with libbitsandbytes_cpu.so . After I decided to download a new build of this dreambooth
`
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary D:\AI\stable-diffusion-webui-master\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...`

**Comment by differentprogramming** [comment]
I just noticed the line "WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!"

I'm installing cuda-toolkit 11.6.2 to match the torch and torchvision libraries (I hope) with the line 
conda install -c "nvidia/label/cuda-11.6.2" cuda-toolkit

from https://anaconda.org/nvidia/cuda-toolkit

It may take a long time to install.

**Comment by differentprogramming** [comment]
Ok, well it must have done more because it took longer and filled up vram...
But I still got the same errors.

**Comment by differentprogramming** [comment]
This might be related to an error I got when installing.
It said that my pytorch version used cuda 11.6 and my torchvision version used cuda 11.3 and I needed them to be the same

So I downloaded torchvision from the nightly.

I bet I should have downgraded torch instead

**Comment by differentprogramming** [comment]
I tried uninstalling and reinstalling torch and torchvision
It did not fix it

**Comment by Art4DD** [comment]
I'm sure the latest update broke the plugin.
I installed it a couple of days ago and everything worked. But not today. We need to wait for d8ahazard to fix it.

**Comment by Slowly-Grokking** [comment]
copy the webui-user-dreambooth.bat from extensions/sd_dreambooth_extension to the root stable-diffusion-webui folder,
and run it.

It should install the versions you need:
torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116

If that doesn't work, make sure make sure delete your venv folder, make sure auto1111 is up to date, and try again.

also use mixed precision: use fp16 or bf16

that works for me on windows 10.

**Comment by differentprogramming** [comment]
I tried that, still got the same errors.

I got rid of the "WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!" warning by running
venv\Scripts\pip install cuda-python

But I still got all the other errors.

Copying libbitsandbytes_cpu.dll and libbitsandbytes_cuda.dll to system32 doesn't stop the error from trying to load the .so file

But mostly it's the "CUDA error: invalid argument" over and over

**Comment by differentprogramming** [comment]
Reverting to a0e43df68dbe61bc2d2c8f4e1ee56b7fc390fea2 did not fix anything

**Comment by Slowly-Grokking** [comment]
I don't recall having a bitsandbytes issue, but have you tried using 0.8.0.dev0 diffusers? i had problems with 0.7.2

https://github.com/ShivamShrirao/diffusers

**Comment by differentprogramming** [comment]
How do I get it to load 0.8.0.dev0?
Setting the line in requirements.txt to "diffusers==0.8.0.dev0" causes an error

 ERROR: Could not find a version that satisfies the requirement diffusers==0.8.0.dev0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1, 0.7.2)
ERROR: No matching distribution found for diffusers==0.8.0.dev0

**Comment by d8ahazard** [comment]
I thought I would be slick and do a diff of the BNB files for windows to ensure I wasn't copying them every time the app runs.

I bet I broke something there. I'll drop an update in an hour or two to fix it.

**Comment by d8ahazard** [comment]
This should resolve the missing bitsandbytes errors.

c5d4d5a09d1e51ff754985438e85811d5e6fb2b5

**Comment by Art4DD** [comment]
I installed the webui and the dreambooth plugin again and I still get the error. It looks like the update didn't fix anything.
```
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary D:\AI\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
```

**Comment by cloudz1lla** [comment]
> This should resolve the missing bitsandbytes errors.
> 
> [c5d4d5a](https://github.com/d8ahazard/sd_dreambooth_extension/commit/c5d4d5a09d1e51ff754985438e85811d5e6fb2b5)

Do we have to re-install everything for this to work now? Or is it possible to update it instead somehow? Many thanks for all your efforts by the way!

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
