### ISSUE TITLE
Model Creation - Running out of memory

### ISSUE THREAD

**Issue by fredconex** [d8ahazard/sd_dreambooth_extension#284]
**Describe the bug**

It's running out of memory when creating a new model, it used to work on older version of the extension.

**Provide logs**

venv "D:\stable-diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 828438b4a190759807f9054932cae3a8b880ddf1
Installing requirements for Web UI
Installing requirements for Dreambooth
Checking Dreambooth requirements.
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is 58bb667b0ac3aa048bd5a99a3bd8d1e3634eae9d
Args: ['extensions\\sd_dreambooth_extension\\install.py']
[*] Diffusers version is 0.7.2.
[*] Torch version is 1.12.1+cu116.
[*] Torch vision version is 0.13.1+cu116.
[*] Transformers version is 4.21.0.
[*] Xformers

Launching Web UI with arguments: --xformers --autolaunch --disable-safe-unpickle
Patching transformers to fix kwargs errors.
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [81761151] from D:\stable-diffusion\stable-diffusion-webui\models\Stable-diffusion\sd-v-1-5\v1-5-pruned-emaonly.ckpt
Global Step: 840000
Using VAE found similar to selected model: D:\stable-diffusion\stable-diffusion-webui\models\Stable-diffusion\sd-v-1-5\v1-5-pruned-emaonly.vae.pt
Loading VAE weights from: D:\stable-diffusion\stable-diffusion-webui\models\Stable-diffusion\sd-v-1-5\v1-5-pruned-emaonly.vae.pt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 2 textual inversion embeddings.
Embeddings: Sounds, wav2png
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating dreambooth model folder: T2
Checkpoint loaded from CheckpointInfo(filename='D:\\stable-diffusion\\stable-diffusion-webui\\models\\Stable-diffusion\\sd-v-1-5\\v1-5-pruned-emaonly.ckpt', title='sd-v-1-5\\v1-5-pruned-emaonly.ckpt [81761151]', hash='81761151', model_name='sd-v-1-5_v1-5-pruned-emaonly', config='D:\\stable-diffusion\\stable-diffusion-webui\\repositories\\stable-diffusion\\configs/stable-diffusion/v1-inference.yaml')
Traceback (most recent call last):
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 931, in extract_checkpoint
    pipe = pipe.to(map_location)
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipeline_utils.py", line 220, in to
    module.to(torch_device)
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 602, in _apply
    param_applied = fn(param)
  File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 12.00 GiB total capacity; 11.09 GiB already allocated; 0 bytes free; 11.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
**Environment**

What OS?

Windows - native

What GPU are you using?

3080ti / 12gb

**Comment by d8ahazard** [comment]
![image](https://user-images.githubusercontent.com/1633844/203070509-a5a240a5-92d1-4461-a7ec-ca9743ed93d0.png)

**Comment by fredconex** [comment]
Thanks that did the trick

**Comment by d8ahazard** [comment]
> Thanks that did the trick

I've just made some changes to the extraction that aims to free VRAM before extracting. 

Care to try creating a checkpoint *without* the --ckptfix flag once?

**Comment by fredconex** [comment]
Yup, it worked

venv "D:\stable-diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 828438b4a190759807f9054932cae3a8b880ddf1
Installing requirements for Web UI
Installing requirements for Dreambooth
Checking Dreambooth requirements.
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is 41f728d823195be2d3cdd0003ed222918f848863
Args: ['extensions\\sd_dreambooth_extension\\install.py']
[*] Diffusers version is 0.7.2.
[*] Torch version is 1.12.1+cu116.
[*] Torch vision version is 0.13.1+cu116.
[*] Transformers version is 4.21.0.
[*] Xformers


Launching Web UI with arguments: --xformers --autolaunch
Patching transformers to fix kwargs errors.
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [1dabd761] from D:\stable-diffusion\stable-diffusion-webui\models\Stable-diffusion\Fred_2500.ckpt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 2 textual inversion embeddings.
Embeddings: Sounds, wav2png
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating dreambooth model folder: Fred2
Checkpoint loaded from CheckpointInfo(filename='D:\\stable-diffusion\\stable-diffusion-webui\\models\\Stable-diffusion\\sd-v-1-5\\v1-5-pruned-emaonly.ckpt', title='sd-v-1-5\\v1-5-pruned-emaonly.ckpt [81761151]', hash='81761151', model_name='sd-v-1-5_v1-5-pruned-emaonly', config='D:\\stable-diffusion\\stable-diffusion-webui\\repositories\\stable-diffusion\\configs/stable-diffusion/v1-inference.yaml')
 Extraction completed.
 Allocated: 7.2GB
 Reserved: 7.2GB

**Comment by d8ahazard** [comment]
Beautiful, thanks.
