### ISSUE TITLE
Unload Face restorer before training

### ISSUE THREAD

**Issue by mykeehu** [d8ahazard/sd_dreambooth_extension#339]
If on the txt2Img page I have the face restorer turned on, and then after that I train, I get an OOM error with 12 GB VRAM, I have to restart the whole SD. It loads it into VRAM and stays there. There is an option in Settings, called "Move face restoration model from VRAM into RAM after processing", this could be used before training, regardless of Settings.

**Comment by d8ahazard** [comment]
I'm already doing that. 

![image](https://user-images.githubusercontent.com/1633844/204142071-f00ea787-2e6f-4aae-be99-a8d0aaa32ff9.png)

**Comment by mykeehu** [comment]
I'll test it later, because it wasn't in yesterday's version, so thank you very much! I'm still getting used to the new layout, but I like it!

**Comment by d8ahazard** [comment]
Actually, I'm a liar. The method is there, but it doesn't do anything,
because I actually need to call "send_model_to", not "to". I've fixed it in
the update I'm working on now, will push later today.

**Comment by d8ahazard** [comment]
The proper "unloading of face models" command has been implemented with 1913bc7. I can't say that this will *absolutely* resolve all memory leaks, but it is the only method natively offered by the base app that I can use on these models - meaning, if more/better memory management is needed in this department, then the right place to address it is on the main WebUI repo.
