### ISSUE TITLE
Cannot create model because OOM

### ISSUE THREAD

**Issue by GunnarQuist** [d8ahazard/sd_dreambooth_extension#359]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: 0b5dcb3d7ce397ad38312dbfc70febe7bb42dcc3
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is 1d7d34110005e7930b589546ff5d82ce16cdcadd
Diffusers version is 0.8.1.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes.

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes.

**Have you updated Dreambooth to the latest revision?**
Yes.

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes.

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**
When I attempt to create a model in Dreambooth I recieve an error message stating that the CUDA is out of memory. This is unusual because I haven't had this problem in the past. In fact, I've been able to train several models. And I continue to train models as long as I use an earlier commit of the Dreambooth extension.

(A clear and concise description of what the bug is)

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

venv "C:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0b5dcb3d7ce397ad38312dbfc70febe7bb42dcc3
Installing requirements for Web UI
Checking Dreambooth requirements...
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is 1d7d34110005e7930b589546ff5d82ce16cdcadd
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.8.1 installed.
[+] transformers version 4.21.0 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.
[ ] xformers version 0.0.14.dev0 installed.

Launching Web UI with arguments: --xformers --theme dark
Patching transformers to fix kwargs errors.
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [a9263745] from C:\AI\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned.ckpt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Extracting checkpoint...
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Allocated 0.0/2.0GB
 Reserved: 0.0/2.0GB

Checkpoint loaded from CheckpointInfo(filename='C:\\AI\\stable-diffusion-webui\\models\\Stable-diffusion\\v1-5-pruned.ckpt', title='v1-5-pruned.ckpt [a9263745]', hash='a9263745', model_name='v1-5-pruned', config='C:\\AI\\stable-diffusion-webui\\v1-inference.yaml')
Checkpoint C:\AI\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned.ckpt has both EMA and non-EMA weights.
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
Error completing request
Arguments: ('eggbaconsausageandspam', 'v1-5-pruned.ckpt [a9263745]', 'ddim', 'runwayml/stable-diffusion-v1-5', '', False) {}
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\AI\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 971, in extract_checkpoint
    pipe = pipe.to(map_location)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipeline_utils.py", line 227, in to
    module.to(torch_device)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 602, in _apply
    param_applied = fn(param)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 11.00 GiB total capacity; 10.01 GiB already allocated; 0 bytes free; 10.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

**Environment**

What OS?
Windows 10

If Windows - WSL or native?
Native

What GPU are you using?
NVIDIA GeForce RTX 2080 Ti

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json
I am unable to train because I cannot create the initial model.

**Comment by d8ahazard** [comment]
Use the --ckptfix command line arg.

See here for an example:

https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/webui-user-dreambooth.bat

**Comment by GunnarQuist** [comment]
Confirmed. This resolved the issue with creating a model. I will attempt to train tomorrow.
Thank you!

**Comment by RomixERR** [comment]
I had a problem `CUDA_ERROR_OUT_OF_MEMORY` start training the model (_and also setting the resolution to 1024 x 1024 for render_) while owning an **RTX3090** card with **24GB** of memory. None of the settings helped.

**The SOLUTION:**
Turned out to be quite simple: You need to enable and increase the windows swap file to 32GB.

**Comment by GunnarQuist** [comment]
For what it's worth, I finally trained a model. Since I have a RTX2080 with 11GB VRAM, tuning parameters are important. Make sure to use 8bit Adam, fp16 mixed precision, memory attention needs to be set to xformers, an do NOT use the train text encoder.

**Comment by RomixERR** [comment]
> > У меня возникла проблема с `CUDA_ERROR_OUT_OF_MEMORY`запуском обучения модели ( _а также установкой разрешения 1024 x 1024 для рендеринга_ ) при наличии карты RTX3090 с **24 ****ГБ** памяти. Никакие настройки не помогли.
> > **РЕШЕНИЕ:** оказалось довольно простым: нужно включить и увеличить файл подкачки windows до 32GB.
> 
> Какая? Мы можем обучить 1024 входных изображения на RTX3090??
> 
> Напишите, пожалуйста, ваши настройки обучения и шаги по увеличению файла подкачки - добавлю в инструкцию.

I meant that when generating images in a resolution of 1024x1024, I caught OOM.
Also, at the start of the model training (512x512), the training did not start.
The reason turned out to be that I had the paging file turned off in Windows 10. I thought that it was not needed, since I have 32 GB of RAM.
