### ISSUE TITLE
no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu

### ISSUE THREAD

**Issue by RoyHammerlin** [d8ahazard/sd_dreambooth_extension#47]
Getting this error from bitsandbytes when running dreambooth in auto1111. I have seen the fix listed [here](https://github.com/TimDettmers/bitsandbytes/blob/main/errors_and_solutions.md#No-kernel-image-available) but it's not clear how to implement it in Windows.

GPU is a 1080ti with 11GB VRAM

```
CUDA SETUP: Loading binary C:\SD\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
 Scheduler Loaded
 Allocated: 0.3GB
 Reserved: 0.3GB

  Total target lifetime optimization steps = 1000
 CPU: False Adam: True, Prec: no, Prior: True, Grad: True, TextTr: True
 Allocated: 4.0GB
 Reserved: 4.1GB

Steps:   0%|                                                                                  | 0/1000 [00:00<?, ?it/s]Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Press any key to continue . . .
```

**Comment by RoyHammerlin** [comment]
I tried the steps mentioned in [this post](https://github.com/d8ahazard/sd_dreambooth_extension/issues/14#issuecomment-1306449270). It did take a little time installing some components for dreambooth, but I am still getting the same error, but with a little more detail after the fault:

```
CUDA SETUP: Loading binary C:\SD\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
 Scheduler Loaded
 Allocated: 0.3GB
 Reserved: 0.3GB

  Total target lifetime optimization steps = 1000
 CPU: False Adam: True, Prec: no, Prior: True, Grad: True, TextTr: True
 Allocated: 4.0GB
 Reserved: 4.1GB

Steps:   0%|                                                                                  | 0/1000 [00:00<?, ?it/s]Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\SD\stable-diffusion-webui\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\SD\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 43, in main
    args.func(args)
  File "C:\SD\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\launch.py", line 837, in launch_command
    simple_launcher(args)
  File "C:\SD\stable-diffusion-webui\venv\lib\site-packages\accelerate\commands\launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\SD\\stable-diffusion-webui\\venv\\Scripts\\python.exe', '.\\launch.py']' returned non-zero exit status 1.
```

**Comment by ZeroCool22** [comment]
Same error, we will get a solution for this?

**Comment by kokakin** [comment]
Same error training with CPU, it occurs on both my laptops after the third step :(

Error:
---
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Scheduler Loaded
 Allocated: 0.0GB
 Reserved: 0.0GB

Steps:   0%|                                                 | 3/2100 [02:44<31:59:29, 54.92s/it, loss=0.0215, lr=5e-6]Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu

**Comment by kokakin** [comment]
unchecking "Use 8bit Adam" solved it for me!

**Comment by d8ahazard** [comment]
Closing and linking to related discussion:

https://github.com/d8ahazard/sd_dreambooth_extension/discussions/99

**Comment by si60** [comment]
> unchecking "Use 8bit Adam" solved it for me!

Please tell me where I can uncheck that.

**Comment by kokakin** [comment]
> > unchecking "Use 8bit Adam" solved it for me!
> 
> Please tell me where I can uncheck that.

It might have changed from last time I've pulled but it was in the same tab where you check "CPU only", sorry I can't check for you since I began using a different tool that doesnt really like this extension.

**Comment by si60** [comment]
Thank you for kindly telling me. If you don't mind, could you tell me what tools you are currently using?

**Comment by kokakin** [comment]
> Thank you for kindly telling me. If you don't mind, could you tell me what tools you are currently using?

No problem :)
I don't think I can link it to you but TheLastBen has done a colab for dreambooth, and also a colab for the automatic UI. The latter has the same tools you would use normally in the UI which implies that this extension "should" work in the colab environment, but I haven't tested it properly, so you will have to try it to see if it works.

**Comment by SystemAvinco** [comment]
> > unchecking "Use 8bit Adam" solved it for me!
> 
> Please tell me where I can uncheck that.

The entry is old, but if someone still has the problem. The "AdamW8Bit" value can be changed to "AdamW" in the "Optimizer" field. That solved the problem for me. Thanks to [kokakin](https://github.com/kokakin) for this.
