### ISSUE TITLE
"RuntimeError: CUDA error: invalid argument" when training

### ISSUE THREAD

**Issue by Baquara** [d8ahazard/sd_dreambooth_extension#513]
Hello,

I am having the same problem as the (closed) issue #115 .
I tried the solutions from that thread, used the .sh file, removed --xformers etc but it is still not working.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.15.dev0+4c06c79.d20221201 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes.
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes.
**Have you updated Dreambooth to the latest revision?**
Yes.
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes.
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK.
**Describe the bug**

I am trying to train using the default settings from the Performance Wizard, but I am getting this:
```

Initializing dreambooth training...
Patching transformers to fix kwargs errors.
/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/generation_utils.py:24: FutureWarning: Importing `GenerationMixin` from `src/transformers/generation_utils.py` is deprecated and will be removed in Transformers v5. Import as `from transformers import GenerationMixin` instead.
  warnings.warn(
Replace CrossAttention.forward to use xformers
Checking concept: {'max_steps': -1, 'instance_data_dir': '/home/privateserver/Coding/sd/dataset/out/', 'class_data_dir': '', 'instance_prompt': '', 'class_prompt': '', 'save_sample_prompt': '', 'save_sample_template': '', 'instance_token': 'sks', 'class_token': 'person', 'num_class_images': 0, 'class_negative_prompt': '', 'class_guidance_scale': 7.5, 'class_infer_steps': 40, 'save_sample_negative_prompt': '', 'n_save_sample': 1, 'sample_seed': -1, 'save_guidance_scale': 7.5, 'save_infer_steps': 40}
Concept requires 0 images.
 Loaded model. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary /home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
 Scheduler, EMA Loaded. 
 Allocated: 3.6GB 
 Reserved: 3.7GB 

***** Running training *****
  Num examples = 29
  Num batches each epoch = 29
  Num Epochs = 100
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 2900
  Actual steps: 2900
   Training settings: CPU: False Adam: True, Prec: bf16, Grad: True, TextTr: False EM: False, LR: 2e-06 LORA:False 
 Allocated: 3.6GB 
 Reserved: 3.7GB 

Steps:   0%|                                                                                                                                           | 0/2900 [00:00<?, ?it/s] Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1. 
 Allocated: 4.1GB 
 Reserved: 5.5GB 

Traceback (most recent call last):
  File "/home/privateserver/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1041, in main
    accelerator.backward(loss)
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1314, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 146, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/home/privateserver/xformers/xformers/ops/memory_efficient_attention.py", line 422, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "/home/privateserver/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |    4180 MB |    5505 MB |   20177 MB |   15997 MB |
|       from large pool |    4103 MB |    5387 MB |   19734 MB |   15630 MB |
|       from small pool |      77 MB |     119 MB |     443 MB |     366 MB |
|---------------------------------------------------------------------------|
| Active memory         |    4180 MB |    5505 MB |   20177 MB |   15997 MB |
|       from large pool |    4103 MB |    5387 MB |   19734 MB |   15630 MB |
|       from small pool |      77 MB |     119 MB |     443 MB |     366 MB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |    5586 MB |    5586 MB |    8368 MB |    2782 MB |
|       from large pool |    5460 MB |    5460 MB |    8162 MB |    2702 MB |
|       from small pool |     126 MB |     126 MB |     206 MB |      80 MB |
|---------------------------------------------------------------------------|
| Non-releasable memory |    1179 MB |    1260 MB |   18897 MB |   17718 MB |
|       from large pool |    1170 MB |    1239 MB |   18379 MB |   17208 MB |
|       from small pool |       8 MB |      37 MB |     518 MB |     509 MB |
|---------------------------------------------------------------------------|
| Allocations           |    1434    |    1723    |    6158    |    4724    |
|       from large pool |     422    |     542    |    2157    |    1735    |
|       from small pool |    1012    |    1184    |    4001    |    2989    |
|---------------------------------------------------------------------------|
| Active allocs         |    1434    |    1723    |    6158    |    4724    |
|       from large pool |     422    |     542    |    2157    |    1735    |
|       from small pool |    1012    |    1184    |    4001    |    2989    |
|---------------------------------------------------------------------------|
| GPU reserved segments |     191    |     191    |     342    |     151    |
|       from large pool |     128    |     128    |     239    |     111    |
|       from small pool |      63    |      63    |     103    |      40    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |      84    |     163    |    2097    |    2013    |
|       from large pool |      28    |      61    |    1163    |    1135    |
|       from small pool |      56    |     103    |     934    |     878    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|

 CLEANUP:  
 Allocated: 4.1GB 
 Reserved: 5.5GB 

 Cleanup completed. 
 Allocated: 4.1GB 
 Reserved: 5.2GB 

 Cleanup Complete. 
 Allocated: 4.1GB 
 Reserved: 5.2GB 

Steps:   0%|                                                                                                                                           | 0/2900 [00:01<?, ?it/s]
 Training completed, reloading SD Model. 
 Allocated: 0.0GB 
 Reserved: 4.1GB 

Memory output: {}
 Restored system models. 
 Allocated: 2.7GB 
 Reserved: 4.1GB 

Returning result: Training finished. Total lifetime steps: 0 



```

**Provide logs**

See above.

**Environment**

What OS?

Arch Linux, 6.0.11-arch1-1

If Windows - WSL or native?

Native Linux.

What GPU are you using?

RTX 3060 12GB

**Screenshots/Config**

![image](https://user-images.githubusercontent.com/9168959/207234430-dc5a604a-ee54-414a-8201-97fdb0937b0a.png)

**Comment by poondoggle** [comment]
I am also seeing this bug on a new install. Everything else is working other than Dreambooth training.

**Comment by Borzik** [comment]
I get this error when I'm training using SD 1.5, but SD 2.0 works fine with the same settings

**Comment by Borzik** [comment]
Looks like there's some incompatibility with the newest version of xformers, and 0.012 or 0.0.13 releases don't work as well. 

I've installed this version and it works:
```
pip3.10 install -v -U git+https://github.com/facebookresearch/xformers.git@47ab8b812fbc0518eb6b630440548c1ff7915500#egg=xformers
```

**Comment by keyserxose** [comment]
Also seeing this issue on Arch Linux, tested fix suggested by @Borzik but no luck

**Comment by ekeric13** [comment]
i get this when I mark the memory attention as "xformers" instead of "default".
The thing is I am able to get xformers to install if i follow the instructions:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Xformers
and then also run this command:
```
pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116
```
Boots fine when I pass the `--xformers` flag.

Just messes up in the context of the dreambooth extensions.

I tried re-installing with what @keyserxose did but that didn't work for me. 

I am on ubuntu 20, using python 3.8, NVIDIA A10, nvcc shows cuda version 11.6 but nvidia-smi shows cuda version 11.7 so not really sure what cuda version but i think the nvcc one matters more??

**Comment by keyserxose** [comment]
> i get this when I mark the memory attention as "xformers" instead of "default". The thing is I am able to get xformers to install if i follow the instructions: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Xformers and then also run this command:
> 
> ```
> pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116
> ```
> 
> Boots fine when I pass the `--xformers` flag.
> 
> Just messes up in the context of the dreambooth extensions.
> 
> I tried re-installing with what @keyserxose did but that didn't work for me.
> 
> I am on ubuntu 20, using python 3.8, NVIDIA A10, nvcc shows cuda version 11.6 but nvidia-smi shows cuda version 11.7 so not really sure what cuda version but i think the nvcc one matters more??

Based on my experience, Dreambooth does not work with Cuda 11.6, you will need to install version 11.3, make sure that you have torch and torchvision installed with cuda 11.3 support, those are the default versions when installing stable-diffusion-webui, so you could achieve that by re-installing, otherwise the below command should also work

    install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113

Also, ignore the output from nvidia-smi, nvcc will give the correct one.

**Comment by ekeric13** [comment]
I have dreambooth working on cuda 11.6. My issue is applying xformers to it.
As mentioned I am able to apply xformers to the inference stage using automatic1111.
I do want it to train faster though so I will investigate what you say at some point since it is painful waiting ~20 minutes for a 2000 step model.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
