### ISSUE TITLE
Bitsandbytes Error

### ISSUE THREAD

**Issue by YakuzaSuske** [d8ahazard/sd_dreambooth_extension#7]
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...

i already have Cuda installed so i don't get what's going on here.
Build cuda_11.6.r11.6/compiler.31057947_0

Maybe it's because i don't have anaconda installed?

**Comment by derekleighstark** [comment]
just got the same error.

**Comment by YakuzaSuske** [comment]
supposedly Nerdy Rodent said it had to do with `export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH`.
Something that it had to be in the pastebin for it to work or something. But i haven't figured it out.

**Comment by d8ahazard** [comment]
> supposedly Nerdy Rodent said it had to do with `export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH`. Something that it had to be in the pastebin for it to work or something. But i haven't figured it out.
> 
> [TimDettmers/bitsandbytes#52](https://github.com/TimDettmers/bitsandbytes/issues/52)

I don't think that's the issue here. That's for WSL, we're trying to do this thing *without* WSL.

I think the issue is just that we need to do 'conda install cudatoolkit=11.3', but getting an issue running from my install script.

**Comment by YakuzaSuske** [comment]
> > supposedly Nerdy Rodent said it had to do with `export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH`. Something that it had to be in the pastebin for it to work or something. But i haven't figured it out.
> > [TimDettmers/bitsandbytes#52](https://github.com/TimDettmers/bitsandbytes/issues/52)
> 
> I don't think that's the issue here. That's for WSL, we're trying to do this thing _without_ WSL.
> 
> I think the issue is just that we need to do 'conda install cudatoolkit=11.3', but getting an issue running from my install script.

Is there another way to install it, if it doesn't work?

**Comment by Evil-Dragon** [comment]
Is this because we don't use conda for the virtual environment? Basically you can't install cudatoolkit using pip which what the issue is. PyTorch doesn't install everything that this needs to run under Windows. I think.

Not an expert on this. I've tried all kinds of instructions from various sources and had no luck getting 8bit Adam to work in Windows with A111 venv.

**Comment by d8ahazard** [comment]
> Is this because we don't use conda for the virtual environment? Basically you can't install cudatoolkit using pip which what the issue is. PyTorch doesn't install everything that this needs to run under Windows. I think.
> 
> Not an expert on this. I've tried all kinds of instructions from various sources and had no luck getting 8bit Adam to work in Windows with A111 venv.

Not 100%, but that's what I'm leaning towards as the issue? Seems like we might need to manually use conda to install cuda-toolkit to the venv, or figure out why it's failing from within the install.py script.

**Comment by Raibeat** [comment]
I fixed this by changing the line in cextension.py:

binary_name = evaluate_cuda_setup()

to hardcode the cuda DLL path (the one in the bitsandbytes site packages folder)

**Comment by LaikaSa** [comment]
I think there is already a solution for this in Windows here: https://github.com/TimDettmers/bitsandbytes/issues/30#issuecomment-1257676341
Basically, you download 2 dll files from this repo: https://github.com/DeXtmL/bitsandbytes-win-prebuilt
and drop them both into webui's sitepackage bitandbytes folder, should be following: stable-diffusion-webui\venv\lib\site-packages\bitsandbytes
After that, replace cextension.py file in the same folder with this: https://pastebin.com/jjgxuh8V
and go to cuda_setup folder, replace the main.py file with this: https://pastebin.com/BsEzpdpw
That is all, problem solved, I tried and no more CUDA_SETUP: WARNING!

**Comment by d8ahazard** [comment]
Found the problem, as LaikaSA pointed out.

I was copying the main.py to the wrong spot.

Should be fixed and working now on windoze with [c42b4f3](https://github.com/d8ahazard/sd_dreambooth_extension/commit/c42b4f3776a4f18ddee01af7864c0400c9697e40)

**Comment by YakuzaSuske** [comment]
> Found the problem, as LaikaSA pointed out.
> 
> I was copying the main.py to the wrong spot.
> 
> Should be fixed and working now on windoze with [c42b4f3](https://github.com/d8ahazard/sd_dreambooth_extension/commit/c42b4f3776a4f18ddee01af7864c0400c9697e40)

Yhea it worked, but now i got CUDA out of memory on my 30880TI, however disabling `Text encoder` fixed it and now its training. Running at 11.7 GB /12.

**Comment by YakuzaSuske** [comment]
Now i got this.

Traceback (most recent call last):
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 256, in start_training
    trained_steps = main(config)
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 796, in main
    text_enc_model = CLIPTextModel.from_pretrained(args.model_name,
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\transformers\modeling_utils.py", line 1966, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\transformers\models\clip\configuration_clip.py", line 133, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\transformers\configuration_utils.py", line 559, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\transformers\configuration_utils.py", line 614, in _get_config_dict
    resolved_config_file = cached_file(
  File "C:\SUPER_SD_2.0\stable-diffusion-webui-master\venv\lib\site-packages\transformers\utils\hub.py", line 424, in cached_file
    raise EnvironmentError(
OSError: Luvelia is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

**Comment by d8ahazard** [comment]
> line 796, in main

I see the issue. Should be fixed with 1ddfcfc

**Comment by YakuzaSuske** [comment]
> > line 796, in main
> 
> I see the issue. Should be fixed with [1ddfcfc](https://github.com/d8ahazard/sd_dreambooth_extension/commit/1ddfcfc5219f9a716a3a880b8e66064f08487b72)

So far its fixed, yhea, it generated till 100 steps as a test and it successfully made an image and saved a ckpt file.

**Comment by d8ahazard** [comment]
> > > line 796, in main
> > 
> > 
> > I see the issue. Should be fixed with [1ddfcfc](https://github.com/d8ahazard/sd_dreambooth_extension/commit/1ddfcfc5219f9a716a3a880b8e66064f08487b72)
> 
> So far its fixed, yhea, it generated till 100 steps as a test and it successfully made an image and saved a ckpt file. However....it got stuck on a loop saying training complete? and it kept saving a ckpt file every 1 step.

Wheeee!

Allright, I'll se what I did wrong now. :P

**Comment by YakuzaSuske** [comment]
> > > > line 796, in main
> > > 
> > > 
> > > I see the issue. Should be fixed with [1ddfcfc](https://github.com/d8ahazard/sd_dreambooth_extension/commit/1ddfcfc5219f9a716a3a880b8e66064f08487b72)
> > 
> > 
> > So far its fixed, yhea, it generated till 100 steps as a test and it successfully made an image and saved a ckpt file. However....it got stuck on a loop saying training complete? and it kept saving a ckpt file every 1 step.
> 
> Wheeee!
> 
> Allright, I'll se what I did wrong now. :P

Forgot to mention it only happened clicking the blue button to restore after hitting cancel and then train again from 100

**Comment by d8ahazard** [comment]
> > > > > line 796, in main
> > > > 
> > > > 
> > > > I see the issue. Should be fixed with [1ddfcfc](https://github.com/d8ahazard/sd_dreambooth_extension/commit/1ddfcfc5219f9a716a3a880b8e66064f08487b72)
> > > 
> > > 
> > > So far its fixed, yhea, it generated till 100 steps as a test and it successfully made an image and saved a ckpt file. However....it got stuck on a loop saying training complete? and it kept saving a ckpt file every 1 step.
> > 
> > 
> > Wheeee!
> > Allright, I'll se what I did wrong now. :P
> 
> Forgot to mention it only happened clicking the blue button to restore after hitting cancel and then train again from 100

Can you post the parameters it spits out in the console when you start training after doing this?

**Comment by YakuzaSuske** [comment]
> 

let me check if i can replicate it...

**Comment by YakuzaSuske** [comment]
after pressing cancel it gets stuck on a loop

**Comment by ShinkoNet** [comment]
Doesn't work.

`Exception importing 8bit adam: cannot import name 'CUDASetup' from partially initialized module 'bitsandbytes.cextension' (most likely due to a circular import)`

However, the same DLLs work with geocine's version because that force installs cu116

`pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116`

how can I do this for this extension?

**Comment by d8ahazard** [comment]
Just added this same bit in install.py via 9e7ec85

**Comment by ShinkoNet** [comment]
Great. Now this should work on windows fine.

**Comment by YakuzaSuske** [comment]
Now we need a good training guide, i'm getting confused and sometimes bad results, mostly because i don't know how to train this well.

**Comment by d8ahazard** [comment]
That's the plan!

For completeness, I'd probably want to add a custom script that calls
launch.py from venv using accelerate launch instead of python. Otherwise,
yep. :D

**Comment by d8ahazard** [comment]
I'm going to mark this as closed. It *may* be necessary to specify a custom torch cmd in webui-user.bat, which I will document briefly in the readme. But, I can get bnb to load and run fine now, so we should be good here.

**Comment by d8ahazard** [comment]
Readme has been updated with installation instructions, but the trick to update CUDA (if needed) is to add this to your webui-user.bat file:

`set TORCH_COMMAND="pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"`

**Comment by roperi** [comment]
@d8ahazard 

I'm a bit confused. 

Automatic1111 suggest this in its `webui-user.sh` (I'm a linux user):

`export TORCH_COMMAND="pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113"`

But you suggests this other one (for Windows users at least):

`TORCH_COMMAND="pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"`

Is Automatic1111 in the wrong? Shoud he/she use cu116 too?

Also, it seems a bit arbitrary to install one cuda version or another one without checking our own systems. So shouldn't the CUDA version be the one our own system has (i.e. nvcc --version)?  Or am I missing something?  Thanks in advance!

**Comment by roperi** [comment]
> 8-bit optimizers and quantization: NVIDIA Maxwell GPU or newer (>=GTX 9XX).

So if I'm not mistaken choosing 8-bit adam will fail if you don't have those NVIDIA specs.

**Comment by GioPetro** [comment]
Similar issues taking place with newer versions now.
Anyone has a solution for CUDA 11.7 + ? Talking about bitsandbytes on windows (11) and cuda accel.
Thanks

**Comment by SiriumLA** [comment]
Possible solution for Windows users:
- Go to ...\stable-diffusion-webui\venv\Lib\site-packages
- Delete the folder "bitsandbytes"
- Use the bitsandbytes version with the following link:
     https://pypi.org/project/bitsandbytes-windows/
- Install the version and ensure it was added to site-packages of stable diffusion
- If you use xformers ensure you use version 0.0.22 in requirements.txt (xformers==0.0.22)

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
