### ISSUE TITLE
Why can't I train with LORA? a few days ago it worked with the same configuration and now it doesn't work since the interface changed

### ISSUE THREAD

**Issue by jojuMX** [d8ahazard/sd_dreambooth_extension#706]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 8708eb3c192fed7690176e3bd7dec1106cf3f0c2
SD-WebUI revision: cca6e5212ddd77be7efdce2c27e475d3af436d85

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.

Installing requirements for dataset-tag-editor [onnxruntime-gpu]

Launching Web UI with arguments: --xformers

Custom model name is
Starting Dreambooth training...
Initializing dreambooth training...
Replace CrossAttention.forward to use xformers
Injecting trainable lora...
prepare train images.
20 train images with repeating.
0 reg images.
prepare dataset
Preparing dataset with buckets...
100%|██████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 119.12it/s]
Bucket 0: Resolution (216, 768), Count: 0
Bucket 1: Resolution (280, 768), Count: 0
Bucket 2: Resolution (344, 768), Count: 0
Bucket 3: Resolution (408, 768), Count: 0
Bucket 4: Resolution (472, 768), Count: 0
Bucket 5: Resolution (536, 768), Count: 0
Bucket 6: Resolution (600, 768), Count: 0
Bucket 7: Resolution (664, 768), Count: 0
Bucket 8: Resolution (728, 768), Count: 0
Bucket 9: Resolution (768, 216), Count: 0
Bucket 10: Resolution (768, 280), Count: 0
Bucket 11: Resolution (768, 344), Count: 0
Bucket 12: Resolution (768, 408), Count: 0
Bucket 13: Resolution (768, 472), Count: 0
Bucket 14: Resolution (768, 536), Count: 0
Bucket 15: Resolution (768, 600), Count: 0
Bucket 16: Resolution (768, 664), Count: 0
Bucket 17: Resolution (768, 728), Count: 0
Bucket 18: Resolution (768, 768), Count: 20
Sched breakpoint is 150
  ***** Running training *****
  Instance Images: 20
  Class Images: 0
  Total Examples: 20
  Num batches each epoch = 20
  Num Epochs = 50
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 20
  Total optimization steps = 1000
  Total training steps = 1000
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: True, Adam: True, Prec: fp16
  Gradient Checkpointing: True, Text Enc Steps: 50.0
  EMA: False
  LR: 6e-06)
Steps:   0%|                                                                               | 0/1000 [00:00<?, ?it/s]OOM Detected, reducing batch/grad size to 0/1.
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 86, in decorator
    return function(batch_size, grad_size, *args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 904, in inner_loop
    accelerator.backward(loss)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 1314, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 146, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 114.00 MiB (GPU 0; 8.00 GiB total capacity; 6.93 GiB already allocated; 0 bytes free; 7.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   0%|                                                                               | 0/1000 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 569, in start_training
    result = main(config, use_subdir=use_subdir, lora_model=lora_model_name,
  File "D:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1024, in main
    return inner_loop()
  File "D:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 84, in decorator
    raise RuntimeError("No executable batch size found, reached zero.")
RuntimeError: No executable batch size found, reached zero.
Training completed, reloading SD Model.
Restored system models.
Returning result: Exception training model: No executable batch size found, reached zero.

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

yes¡¡

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

too many times¡¡

**Have you updated Dreambooth to the latest revision?**

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**

**Describe the bug**

(A clear and concise description of what the bug is)

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**

What OS?

Windows 11 Pro
21H2
22000.1335

If Windows - WSL or native?

What GPU are you use?

Nvidia Quadro RTX 4000 8 GB VRam

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by ZeroCool940711** [comment]
They practically made it so on the latest version you can't run this extension on an 8GB GPU even with LORA enabled, they killed it for those of us with 8GB GPUs. I recommend you go back to an older version, [this commit](https://github.com/d8ahazard/sd_dreambooth_extension/tree/c5cb58328c555ac27679422b1da940a9b19de6f2) works fine for me, it was before the big changes they made to the interface.

**Comment by MatMond** [comment]
I ran into the exact same issue on Win10/RTX 2070 and Win10/RTX 3080.
After replacing the current version of dreambooth with the commit mentionned by @ZeroCool940711 , evrething's back to normal !

**Comment by d8ahazard** [comment]
> They practically made it so on the latest version you can't run this extension on an 8GB GPU even with LORA enabled, they killed it for those of us with 8GB GPUs. I recommend you go back to an older version, [this commit](https://github.com/d8ahazard/sd_dreambooth_extension/tree/c5cb58328c555ac27679422b1da940a9b19de6f2) works fine for me, it was before the big changes they made to the interface.

Hey, thanks for the super constructive and helpful comments. 

Just to clarify - "They" is me. One person, working on this $hit some 12 hours a day or more.

Also, reverting doesn't help fix the problem. Telling people to revert doesn't fix the problem. Hell, opening issues with subjects that don't actually state what the problem is...doesn't help fix the problem.

**Comment by cogfilms-3D** [comment]
> They practically made it so on the latest version you can't run this extension on an 8GB GPU even with LORA enabled, they killed it for those of us with 8GB GPUs. I recommend you go back to an older version, [this commit](https://github.com/d8ahazard/sd_dreambooth_extension/tree/c5cb58328c555ac27679422b1da940a9b19de6f2) works fine for me, it was before the big changes they made to the interface.

**Comment by PauloRodrigues33** [comment]
> Matmond, thanks for this info because I have been struggling with this for the last week. Compounded of course by the disappearance of Automatic1111 for several days and multiple reinstalls. I tried to go back to previous versions of both this extension and automatic1111 with no success. in fact it mucked things up probably because I really didn't know what I was doing. So how should I go back to this build?
> 
> * Is it just the extension. and how do I do that?
> * Do I have to go back on automatic1111 and dreambooth extension, and if so how can you do that manually?
> 
> Perhaps as just a little respectful advice to d8ahazrd, document, document, document. Especially if changes are made that will impact users without there knowledge. I know its always difficult but coming from management in the IT industry for over 40 years, I know how important it is to carry the userbase with you.
> 
> --------------------------------------------------------------UPDATE--------------------------------------------------------------------
> 
> Someone else responded on another thread with the answers to this question. If you want to go back to a working version of this dreambooth extension for automatic1111. Click this link [[https://github.com/d8ahazard/sd_dreambooth_extension/tree/c5cb58328c555ac27679422b1da940a9b19de6f2](url)] to go to a revision that works for me. Thats the 22 December dreambooth extension for automatic1111. Then :-
> 
> 1. Click on the green link and download the zip of that commit.
> 2. You might want to take a backup of C:\stable-diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension before you take the next step.
> 3. Unzip it, and overwrite, to the C:\stable-diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension directory.
> 4. Open automatic1111 and enable Dreambooth extension. DONOT update the extention or it will reload the NON-WORKING latest commit.
> 5. I always close and restart automatic1111, sometimes twice, to ensure all dependances load correctly before using Dreambooth training.
> 
> You should be able to train using LORA on an 8Gb card again.
> 
> Hope this helps anyone in a similar position.
> 
> cogfilms3D

Unfortunately, doesn't work with the latest version of Stable Diffusion, "Create model" button do nothing, "Train" button just print the path of image classifiers.

**Comment by dustsoar** [comment]
> Matmond, thanks for this info because I have been struggling with this for the last week. Compounded of course by the disappearance of Automatic1111 for several days and multiple reinstalls. I tried to go back to previous versions of both this extension and automatic1111 with no success. in fact it mucked things up probably because I really didn't know what I was doing. So how should I go back to this build?
> 
> * Is it just the extension. and how do I do that?
> * Do I have to go back on automatic1111 and dreambooth extension, and if so how can you do that manually?
> 
> Perhaps as just a little respectful advice to d8ahazrd, document, document, document. Especially if changes are made that will impact users without there knowledge. I know its always difficult but coming from management in the IT industry for over 40 years, I know how important it is to carry the userbase with you.
> 
> --------------------------------------------------------------UPDATE--------------------------------------------------------------------
> 
> Someone else responded on another thread with the answers to this question. If you want to go back to a working version of this dreambooth extension for automatic1111. Click this link [[https://github.com/d8ahazard/sd_dreambooth_extension/tree/c5cb58328c555ac27679422b1da940a9b19de6f2](url)] to go to a revision that works for me. Thats the 22 December dreambooth extension for automatic1111. Then :-
> 
> 1. Click on the green link and download the zip of that commit.
> 2. You might want to take a backup of C:\stable-diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension before you take the next step.
> 3. Unzip it, and overwrite, to the C:\stable-diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension directory.
> 4. Open automatic1111 and enable Dreambooth extension. DONOT update the extention or it will reload the NON-WORKING latest commit.
> 5. I always close and restart automatic1111, sometimes twice, to ensure all dependances load correctly before using Dreambooth training.
> 
> You should be able to train using LORA on an 8Gb card again.
> 
> Hope this helps anyone in a similar position.
> 
> cogfilms3D

Could you tell us which version of stable-diffusion-webui suits this build, new version of stable-diffusion seems not work with old DB.
