### ISSUE TITLE
OOM error when generate previews - 'No executable batch size found, reached zero.'

### ISSUE THREAD

**Issue by mykeehu** [d8ahazard/sd_dreambooth_extension#760]
`
Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 55880895d6bdf3596db815cb62e22969e9910b7b
SD-WebUI revision: 3e20244b0fea10988cf5ad8a2fbe190ac47a5049

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

When the training would generate preview images, I get an OOM error. The training was running fine until then.

```
Starting Dreambooth training...
Initializing dreambooth training...
Replace CrossAttention.forward to use xformers
Instance Bucket 0: Resolution (512, 512), Count: 30
Target Bucket 0: Resolution (512, 512), Count: 0
We need a total of 0 images.
Nothing to generate.
Preparing dataset
Preparing dataset
Preparing Dataset (With Caching)
100%|██████████████████████████████████████████| 30/30 [00:03<00:00,  7.93it/s]
Train Bucket 1: Resolution (512, 512), Count: 30
Total images: 30
Total dataset length (steps): 30
Sched breakpoint is 0
  ***** Running training *****
  Instance Images: 30
  Class Images: 0
  Total Examples: 30
  Num batches each epoch = 30
  Num Epochs = 100
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 20
  Total optimization steps = 3000
  Total training steps = 3000
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Adam: True, Prec: bf16
  Gradient Checkpointing: True
  EMA: True
  LR: 2e-06)
Generating Samples:   0%| | 0/4 [00:00<?, ?it/s, loss=0.00784, loss_avg=0.101, Exception saving sample: CUDA out of memory. Tried to allocate 576.00 MiB (GPU 0; 12.00 GiB total capacity; 10.74 GiB already allocated; 0 bytes free; 11.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 711, in save_weights
    s_image = s_pipeline(c.prompt, num_inference_steps=c.steps,
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 534, in __call__
    image = self.decode_latents(latents)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 341, in decode_latents
    image = self.vae.decode(latents).sample
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\vae.py", line 605, in decode
    decoded = self._decode(z).sample
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\vae.py", line 577, in _decode
    dec = self.decoder(z)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\vae.py", line 217, in forward
    sample = up_block(sample)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1331, in forward
    hidden_states = resnet(hidden_states, temb=None)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\resnet.py", line 464, in forward
    hidden_states = self.conv1(hidden_states)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 576.00 MiB (GPU 0; 12.00 GiB total capacity; 10.74 GiB already allocated; 0 bytes free; 11.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Generating Samples:  25%|▎| 1/4 [00:09<00:29,  9.68s/it, loss=0.00784, loss_avgOOM Detected, reducing batch/grad size to 0/1.
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 116, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 936, in inner_loop
    check_save(progress_bar, True)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 568, in check_save
    save_weights(save_image, save_model, save_snapshot, save_checkpoint, save_lora, pbar)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 769, in save_weights
    optim_to(optimizer, accelerator.device)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 508, in optim_to
    inplace_move(subparams, device)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 498, in inplace_move
    obj.data = obj.data.to(target)
RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 12.00 GiB total capacity; 11.24 GiB already allocated; 0 bytes free; 11.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Generating Samples:  50%|▌| 2/4 [00:10<00:10,  5.48s/it, loss=0.00784, loss_avg
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 561, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 973, in main
    return inner_loop()
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 114, in decorator
    raise RuntimeError("No executable batch size found, reached zero.")
RuntimeError: No executable batch size found, reached zero.
Training completed, reloading SD Model.
Restored system models.
Returning result: Exception training model: 'No executable batch size found, reached zero.'.
```

**Environment**

What OS? Windows

If Windows - WSL or native? Native

What GPU are you using? RTX 3060 12 GB

**Comment by mykeehu** [comment]
I tested it with the 84c9359cfb5b6266685e91053871dc115be3ae36 version, and it threw an error like this, so I'm going backwards. Could it be a SD problem? Maybe the memory is not cleared before training? I only get this error when generating images, the workout was running until then.

```
Starting Dreambooth training...
Initializing dreambooth training...
Replace CrossAttention.forward to use xformers
CUDA SETUP: Loading binary H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
prepare train images.
30 train images with repeating.
0 reg images.
prepare dataset
Caching latents with buckets...
100%|██████████████████████████████████████████| 30/30 [00:15<00:00,  1.98it/s]
Bucket 0: Resolution (144, 512), Count: 0
Bucket 1: Resolution (208, 512), Count: 0
Bucket 2: Resolution (272, 512), Count: 0
Bucket 3: Resolution (336, 512), Count: 0
Bucket 4: Resolution (400, 512), Count: 0
Bucket 5: Resolution (464, 512), Count: 0
Bucket 6: Resolution (512, 144), Count: 0
Bucket 7: Resolution (512, 208), Count: 0
Bucket 8: Resolution (512, 272), Count: 0
Bucket 9: Resolution (512, 336), Count: 0
Bucket 10: Resolution (512, 400), Count: 0
Bucket 11: Resolution (512, 464), Count: 0
Bucket 12: Resolution (512, 512), Count: 30
Sched breakpoint is 0
  ***** Running training *****
  Instance Images: 30
  Class Images: 0
  Total Examples: 30
  Num batches each epoch = 30
  Num Epochs = 95
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 30
  Total optimization steps = 2850
  Total training steps = 2850
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Adam: True, Prec: fp16
  Gradient Checkpointing: True, Text Enc Steps: 20.0
  EMA: True
  LR: 2e-06)
Steps:   5%| | 150/2850 [03:03<1:01:50,  1.37s/it, loss=0.288, loss_avg=0.137, Exception saving sample: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.23 GiB already allocated; 0 bytes free; 11.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 787, in save_weights
    s_image = s_pipeline(c.prompt, num_inference_steps=c.steps,
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 517, in __call__
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 490, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\amp\autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 392, in forward
    sample = self.mid_block(sample, emb, encoder_hidden_states=encoder_hidden_states)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 412, in forward
    hidden_states = self.resnets[0](hidden_states, temb)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\resnet.py", line 467, in forward
    temb = self.time_emb_proj(self.nonlinearity(temb))[:, :, None, None]
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.23 GiB already allocated; 0 bytes free; 11.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen DPI.
   QT_SCALE_FACTOR to set the application global scale factor.
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 569, in start_training
    result = main(config, use_subdir=use_subdir, lora_model=lora_model_name,
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1024, in main
    return inner_loop()
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 86, in decorator
    return function(batch_size, grad_size, *args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 888, in inner_loop
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 490, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\amp\autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 381, in forward
    sample, res_samples = downsample_block(
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 618, in forward
    hidden_states = downsampler(hidden_states)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\resnet.py", line 188, in forward
    hidden_states = self.conv(hidden_states)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
Steps:   5%| | 150/2850 [03:10<57:08,  1.27s/it, loss=0.288, loss_avg=0.137, lr
Training completed, reloading SD Model.
Restored system models.
Returning result: Exception training model: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
```

**Comment by mykeehu** [comment]
I can't downgrade to an older version because of the SD, which has updated components. Could the preview image generation be a memory problem by SD?

**Comment by mykeehu** [comment]
@jackmott here are my training settings, they work fine:

![image](https://user-images.githubusercontent.com/6390413/211804890-c1641359-1ab0-4982-b286-dfa2c20a4333.png)
![image](https://user-images.githubusercontent.com/6390413/211805011-28654de3-6fb7-4786-89c3-43116d204a03.png)
![image](https://user-images.githubusercontent.com/6390413/211805081-9c8ecf5a-95af-4a89-9f59-daac7320bca0.png)

True, it used to be able to generate 8 batch classification images, now it can only generate one, so there must be a problem with the generation, but whether in the DB or in SD is a good question. 
I'll check at the end of the training if I can do 8 batch image generation in SD, but I think I can do it...

**Comment by jackmott** [comment]
Maybe your memory attention xformers settings is helping, appears to be the only difference. I will try that, but would still be good to track down what is using more memory now.

**Comment by mykeehu** [comment]
@jackmott I am very glad that this solved your problem! :) 

However, the blind training is very annoying, so I always have to wait until the end to see if I've done it...

**Comment by Boris-SS** [comment]
HI, All! Using dreambooth for the very first time, and can`t run traing becouse of error = RuntimeError("No executable batch size found, reached zero.")

No ideas how to fix it, could somebody help please?

**Comment by jackmott** [comment]
@Boris-SS probably not best to turn this into a how to use dreambooth discussion, but with a 10gb card you have to turn a lot of settings down, If you see the screenshot above, uncheck "use EMA" and bring the step ratio of text encoding down to 0. That might work, but quality will suffer.  I think you can also try the LORA setting.   the error you are getting is running out of memory.

**Comment by mykeehu** [comment]
Now it's gone on first ckpt generation for me. New model, parameters are almost the same, but I didn't give the model a unique name under Custom model name...

```
Starting Dreambooth training...
Initializing dreambooth training...
Replace CrossAttention.forward to use xformers
Instance Bucket 0: Resolution (512, 512), Count: 30
Target Bucket 0: Resolution (512, 512), Count: 0
We need a total of 0 images.
Nothing to generate.
CUDA SETUP: Loading binary H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Preparing dataset
Preparing dataset
Preparing Dataset (With Caching)
100%|██████████████████████████████████████████| 30/30 [00:07<00:00,  3.92it/s]
Train Bucket 1: Resolution (512, 512), Count: 30
Total images: 30
Total dataset length (steps): 30
Sched breakpoint is 0
  ***** Running training *****
  Instance Images: 30
  Class Images: 0
  Total Examples: 30
  Num batches each epoch = 30
  Num Epochs = 150
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 150
  Total optimization steps = 4500
  Total training steps = 4500
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Adam: True, Prec: fp16
  Gradient Checkpointing: True
  EMA: True
  LR: 2e-06)
Compiling Checkpoint:  75%|▊| 3/4 [00:41<00:14, 14.92s/it, loss=0.00485, loss_aTraceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 856, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 486, in <lambda>
    fn=lambda: check_progress_call(),
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 98, in check_progress_call
    preview = gr.update(visible=True, value=image[0])
IndexError: list index out of range
Steps:   7%| | 301/4500 [00:01<00:22, 184.61it/s, loss=0.0195, loss_avg=0.0195,OOM Detected, reducing batch/grad size to 0/1.
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 116, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 873, in inner_loop
    ema_unet.step(unet.parameters())
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 348, in step
    tmp = self.decay * (s_param - param)
RuntimeError: CUDA out of memory. Tried to allocate 114.00 MiB (GPU 0; 12.00 GiB total capacity; 10.97 GiB already allocated; 0 bytes free; 11.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   7%| | 301/4500 [00:03<00:51, 81.36it/s, loss=0.0195, loss_avg=0.0195,
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 561, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 973, in main
    return inner_loop()
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 114, in decorator
    raise RuntimeError("No executable batch size found, reached zero.")
RuntimeError: No executable batch size found, reached zero.
Training completed, reloading SD Model.
Restored system models.
Returning result: Exception training model: 'No executable batch size found, reached zero.'.
```

**Comment by randaller** [comment]
Same here, for such a long time, started may be 2 weeks ago or so.

**Comment by mykeehu** [comment]
I started a new training without generating a preview image. It would save the first checkpoint at 50%, the save threw this error at 75%, the training continued:

```
Compiling Checkpoint:  75%|▊| 3/4 [00:46<00:16, 16.67s/it, loss=0.325, loss_avgTraceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 856, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 486, in <lambda>
    fn=lambda: check_progress_call(),
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 98, in check_progress_call
    preview = gr.update(visible=True, value=image[0])
IndexError: list index out of range
```

**Comment by mykeehu** [comment]
Today we tried it: if the training contains class images, or tries to generate sample images, I get an OOM error. 
This was not the case in last year's versions. 
For some reason the VRAM demand increases a lot during this time. Isn't there some way to improve this by using virtual VRAM?

**Comment by mykeehu** [comment]
On a clean install, I went all the way back to 53cfe97dcbfa00e6d693e537e2c9a1935b586d66 commit. Something happened here during the save that may have interfered with the image generation. In the ca9c051bb071d2c79b43d8fe5491a31fa4ff1671 commit, there was no OOM error when generating the sample image.

**Comment by DemonSkye** [comment]
> but caches the contents of the entire folder. It's wrong.

Have also been experiencing this since new years patch.

**Comment by mykeehu** [comment]
I'm beginning to wonder what the problem is.
I installed an SD dated 10 December and a DB dated 13 December, nothing else. The training starts with class images, but it can't generate a preview image either. I'm sure it was working in December. 
I also reinstalled the NVIDIA driver from December, that didn't help either. I am at a loss. 
However, the fact is that the December pair ate 2 GB less VRAM.

**Comment by porochickenrye** [comment]
I'm experiencing the same error. Here is another data point when training with absolute bare bone settings and xformers: 

`RuntimeError: CUDA out of memory. **Tried to allocate 58.00 MiB (GPU 0; 14.61 GiB total capacity; 13.12 GiB already allocated; 41.56 MiB free; 13.27 GiB reserved in total by PyTorch**) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by ArcticFaded** [comment]
to add another datapoint ... i get OOM even on an A100 lol 
```
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 79.17 GiB total capacity; 10.36 GiB already allocated; 9.81 MiB free; 10.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by g0lemXIV** [comment]
Same here with A6000 
```RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 47.54 GiB total capacity; 13.82 GiB already allocated; 275.81 MiB free; 14.37 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF```

**Comment by CaptBli** [comment]
I have updated to latest this evening and I still get the similar error:
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 79.17 GiB total capacity; 10.36 GiB already allocated; 9.81 MiB free; 10.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by mjoach** [comment]
I have been struggling with this error over countless revisions despite 24GB of VRAM (Ubuntu 22.04). In my case, it turned out the problem is related to having 2 GPUs installed and I'm guessing it might also be the case for the folks with A100 and similar. So as a temporary measure, try launching the GUI on a single GPU, e.g. as CUDA_VISIBLE_DEVICES=0 python launch.py --xformers
